* <<<105>>> PROBLEM SOLVING AND PROGRAMMING IN PYTHON
:properties:
:author: P.Mirunalini and H.Shahul Hamead
:date: 18 March 2021
:end:

** CO PO MAPPING :noexport:
|                |    | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 | PSO1 | PSO2 | PSO3 |
| CO1            | K3 |   1 |   1 |   0 |   1 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    0 |    2 |    1 |    0 |
| CO2            | K3 |   1 |   2 |   0 |   1 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    0 |    2 |    0 |    0 |
| CO3            | K3 |   1 |   3 |   0 |   1 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    0 |    3 |    0 |    0 |
| CO4            | K3 |   1 |   3 |   0 |   1 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    0 |    2 |    0 |    0 |
| CO5            | K3 |   1 |   2 |   0 |   0 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    0 |    2 |    0 |    0 |
| Score          |    |   5  | 11 |   0 |   5 |   0 |   0 |  0  |   0 |   0 |    0 |    0 |    0 |   11 |    0 |    0 |
| Course Mapping |    |   1 |    3 |  0 |   1 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    0 |    3 |    0 |    0 |

	

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |
		
** COURSE OBJECTIVES
   - To learn algorithmic problem solving techniques.
   - To learn the fundamentals of python programming.
   - To compose programs in Python using conditions, iterationa and decompose a problem into functions
   - To construct programs in Python sequcenced data type.
   - To develop python programs using advanced constructs like dictionaries and files. 

{{{unit}}}
| UNIT I | ALGORITHMIC PROBLEM SOLVING  | 9 |
Logical and Algorithmic Thinking: Logical Thinking -- Algorithmic Thinking;
Problem Solving and Decomposition: Defining the Problem -- Devising the Solution
-- Decomposition; Effective building blocks: Basic Algorithmic Constructs (pseudo code,
flow chart, programming language) -- Program State.

{{{unit}}}
| UNIT II | DATA, EXPRESSION, STATEMENT, CONDITIONAL | 9 |
Data and types: int, float, boolean, string, list; variables,
expressions, statements, simultaneous assignment, precedence of
operators; comments; in-built modules and functions; Conditional:
boolean values and operators, conditional (if), alternative (if-else),
case analysis (if-elif-else).

{{{unit}}}
| UNIT III | ITERATION, FUNCTION, STRINGS | 9 |
Iteration: while, for, break, continue, pass; Functions: function
definition, function call, flow of execution, parameters and
arguments, return values, local and global scope, recursion; Strings:
string slices, immutability, string functions and methods, string
module.

{{{unit}}}
| UNIT IV | LISTS, TUPLES | 9 |
Lists: list operations, list slices, list methods, list loop,
mutability, aliasing, cloning lists, list parameters, nested lists,
list comprehension; Tuples: tuple assignment, tuple as return value,
tuple operations.

{{{unit}}}
| UNIT V | DICTIONARIES, FILES | 9 |
Dictionaries: operations and methods, looping and dictionaries,
reverse lookup, dictionaries and lists; Files: Text files, reading and
writing files, format operator, file names and paths; command line
arguments.

*Total Hours:45*

** COURSE OUTCOMES
After the completion of this course, students will be able to:
- Solve programming problems and express solutions in pseudo code (K3).
- Develop simple programs using basic constructs (K3).
- Construct programs using conditions and iterations decompose a problem into functions. (K3)
- Make use of strings, lists, tuples and  dictionaries data structures (K3).
- Perform Input/Output Operations using files (K3).



** TEXT BOOKS
1. Karl Beecher, ``Computational Thinking -- A beginner's Guide to
   Problem Solving and Programming'', British Computer Society
   (BCS), 2017.
2. Allen B. Downey, ``Think Python: How to Think Like a Computer
   Scientist'', 2nd edition, Green Tea Press, Shroff/O'Reilly
   Publishers, 2015 (http://greenteapress.com/wp/think-python/)
   

** REFERENCES
1. Ashok Namdev Kamthane, Amit Ashok Kamthane, "Programming and Problem Solving 
   with Python",McGraw Hill Education (India) Private Limited,2018.
2. John V Guttag, ``Introduction to Computation and Programming Using
   Python'', MIT Press, 2016.
3. Robert Sedgewick, Kevin Wayne, Robert Dondero, ``Introduction to
   Programming in Python: An Inter-disciplinary Approach'', Pearson
   India Education Services Pvt. Ltd., 2016.
4. Timothy A. Budd, ``Exploring Python'', Mc-Graw Hill Education
   (India) Private Ltd., 2015.
5. Kenneth A. Lambert, ``Fundamentals of Python: First Programs'', 2nd Edition,
   CENGAGE Learning, 2018.
