* PROGRAMMING IN C
:properties:
:author: R S Milton
:date: 28 June 2018
:end:

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |
		
** Course Objectives
   - To solve programming problems in C
   - To use basic programming concepts of C
   - To develop programs using loops, functions, arrays, pointers,
     strings, structures and files

{{{unit}}}
| UNIT I | BASICS | 7 |
Algorithm -- modularity, reusability, maintainability -- Software
engineering fundamentals: project management, feasibility study. Best
practices and guidelines for Programming.  Structure of a C program --
data types -- variables and constants -- operators, expressions,
assignment statements -- input and output statements -- control
statements.

{{{unit}}}
| UNIT II | FUNCTIONS | 6 |
Function prototype -- function definition and call -- passing
parameters -- recursion; Program structure: storage classes --
multi-file programs-- standard library functions.

{{{unit}}}
| UNIT III | ARRAYS AND STRINGS | 6  |
Arrays: declaration, initialization -- multi-dimensional arrays --
passing arrays to functions; Strings: reading and writing strings,
string operations, string library functions.

{{{unit}}} 
| UNIT IV | POINTERS | 6  |
Pointers: pointer operators -- pointer to an array -- array of
pointers -- command line arguments -- pointer to a function -- passing
pointers to functions -- problems in using pointers.

{{{unit}}}
| UNIT V | STRUCTURES | 6 |
User defined data types -- structures -- structures and functions --
array of structures -- pointer to a structure -- type definition
(typedef); Enumerated data type; Choosing suitable data types.

#+BEGIN_COMMENT
Files: opening and closing a data file -- creating a data file --
processing a data file -- unformatted data files -- formatted input
and output -- line input and output -- file error handling; Standard
library functions.
#+END_COMMENT

\hfill *Total Hours: 45*

** Text Books
   1. Byron Gottfried, ``Programming with C'' (Schaum's Outlines Series),
      McGraw-Hill Education, 3rd Edition, 2017
   2. Brian W Kernighan and Dennis M Ritchie, ``The C Programming
      Language'', Pearson Education India, 2nd Edition, 2015

** References
   1. Reema Thareja, ``Programming in C'', Oxford University Press,
      Second Edition, 2016
   2. Yashwant Kanetkar, ``Let Us C'', BPB Publications, 14th Edition, 2016
   3. K. N. King, ``C Programming -- A Modern Approach'', W. W. Norton
      & Company 2nd Edition, 2008

** Course Outcomes
After the completion of this course, students will be able to:
- Write  pseudo-code for solving programming problems. (K3)
- Represent data with suitable structued data types. (K3)
- Develop C programs using appropriate programming constructs. (K4)
- Organize programs into functions and files. (K3)
