* <<<504>>> SOFTWARE ENGINEERING
:properties:
:author: Dr. A. Chamundeswari and Ms. S. Angel Deborah
:date: 
:end:


#+startup: showall

** CO PO MAPPING :noexport:
#+NAME: co-po-mapping
|                |    | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 | PSO1 | PSO2 | PSO3 |
|                |    |  K3 |  K4 |  K5 |  K5 |  K6 |   - |   - |   - |   - |    - |    - |    - |   K5 |   K3 |   K6 |
| CO1            | K2 |   2 |   3 |   2 |   3 |   3 |   0 |   2 |   1 |   0 |    3 |    0 |    2 |    3 |    2 |    1 |
| CO2            | K3 |   2 |   3 |   2 |   3 |   3 |   0 |   2 |   1 |   0 |    3 |    0 |    2 |    3 |    2 |    1 |
| CO3            | K3 |   2 |   3 |   2 |   3 |   3 |   0 |   2 |   1 |   0 |    3 |    0 |    2 |    3 |    2 |    1 |
| CO4            | K2 |   2 |   3 |   3 |   3 |   3 |   0 |   2 |   1 |   0 |    3 |    0 |    2 |    3 |    1 |    1 |
| CO5            | K3 |   2 |   3 |   3 |   3 |   3 |   0 |   2 |   1 |   0 |    3 |    0 |    2 |    3 |    1 |    1 |
| Score          |    |  13 |  10 |   8 |   0 |   5 |   5 |   0 |   5 |   0 |    0 |    0 |    0 |    8 |   13 |    5 |
| Course Mapping |    |   3 |   2 |   2 |   0 |   1 |   1 |   0 |   1 |   0 |    0 |    0 |    0 |    2 |    3 |    1 |


{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- Understand the phases and process  model in a software project mangement
- Understand  a simple software as a service application using architecture framework 
- Build an application using MVC and mobile framework
- Analyze the software requirements and testing of software projects
- Understand the agile and Devops environment

{{{unit}}}
| UNIT I | INTRODUCTION | 9 |
The Software Development Life Cycle : Pre-development phases of the SDLC -- Development specific phases of the SDLC -- Post-development phases of the SDLC; Methodologies Paradigm and practices : Process methodologies -- development paradigms -- development pracictes;


#+begin_comment
Text book 4, chapter 2,4
#+end_comment

{{{unit}}}
| UNIT II | SOFTWARE REQUIREMENT AND RISK | 9 |

Project planning process : Software requirements document; Requirement Engineering Process: Feasibility studies -- Requirements elicitation and analysis -- Requirements validation -- Requirements Management; Software Project Estimation:   Empirical estimation models -- -- Project scheduling; Risk Management: Risk identification -- Risk projection -- Risk mitigation;   


#+begin_comment
Text book 2, chapter 2,3
#+end_comment

{{{unit}}}
| UNIT III | SOFTWARE DESIGN | 9 |
Design Concepts: Design process -- Design concepts -- Design model -- Modeling principles; Architectural Design: Architectural Styles; Simple Styles – Distributed and Networked Architectures – Architecture for Network based Applications – Decentralized Architectures. Architecture of Software Systems involving Internet-of-Things(IoT);Architecture tool. 
 
#+begin_comment
Text book 2 , chapter 4,6
#+end_comment

{{{unit}}}
| UNIT IV | SOFTWARE TESTING | 9 |
Software Testing Fundamentals; Internal and External Views of Testing: White Box Testing --Basis Path Testing -- Control Structure Testing-- Black Box Testing -- Unit Testing -- Integration Testing -- Regression Testing -- Validation Testing -- System Testing -- Security Testing ; Testing tool.


#+begin_comment
Text book 2 , chapter 7,8 
#+end_comment


{{{unit}}}
| UNIT V | AGILE AND DEVOPS | 9 |
Agile Teams : It Takes a Team: Two-Pizza and Scrum --  Using Branches Effectively -- Pull Requests and Code Reviews -- Delivering the Backlog Using Continuous Integration -- Agile Iterations -- Reporting and Fixing Bugs; Dev/Ops -- From Development to Deployment --Three-Tier --Responsiveness, Service Level Objectives, and Apdex -- Releases and Feature Flags -- Monitoring and Finding Bottlenecks --Improving Rendering and Database Performance With Caching;

#+begin_comment
Text book 1 , chapter 10,12
#+end_comment


\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Demonstrate all the phases in software engineering  (K2)
- Compare the architecture to develop an application (k3)
- Choose the suitable framework do develop an application (k3) 
- Categorize the requirements and testing need of the software project (K3)
- Explain the procedure in agile and devops environment (k2)

 


** TEXT BOOKS
1. Armando Fox and David Patterson , Engineering Software as a Service: An Agile Approach Using Cloud Computing Second Edition, 2021
2. Roger S Pressman, Bruce R.Maxin ``Software Engineering -- A Practitioner's Approach'', McGraw-Hill International Edition, Eighth Edition, 2015.
3. Ian Sommerville, ``Software Engineering'', Pearson Education Asia,Tenth Edition, 2015.

** REFERENCES
1. Rajib Mall, ``Fundamentals of Software Engineering'', PHI Learning  Private Limited, Fifth Edition, 2015.
2. Pankaj Jalote, ``Software Engineering, A Precise Approach'', Wiley  India, 2010.
3. Kelkar S A,``Software Engineering'', Prentice Hall of India, 2007.
4. Stephen R Schach, ``Software Engineering'', Tata McGraw-Hill Publishing Company Limited,2007.
