* <<<601>>> INTERNET PROGRAMMING 
:properties:
:author: Dr. B. Prabavathy and Dr. V. S. Felix Enigo
:Date: 24-03-2021
:end:

#+BEGIN_COMMENT
1. Comments for the inclusion and removal of the contents in this syllabus with respect to AU R-2017 have been included along with the units
2. The syllabi for UG and PG are different to a larger extent
3. Course outcomes are specified and aligned with the units 
4. Suggestive experiments are specified in the separate lab course for this subject
5. In Unit-I, Web server vulnerabilities and solutions has been added as suggested by Mr. Karthik
#+END_COMMENT

#+startup: showall
{{{credits}}}
| L | T | P | C | 
| 3 | 0 | 0 | 3 |

** CO PO MAPPING :noexport:
#+NAME: co-po-mapping
|                |    | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 | PSO1 | PSO2 | PSO3 |
|                |    |  K3 |  K4 |  K5 |  K5 |  K6 |   - |   - |   - |   - |    - |    - |    - |   K5 |   K3 |   K6 |
| CO1            | K3 |   2 |   2 |   3 |   0 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    0 |    0 |    0 |    0 |
| CO2            | K3 |   2 |   2 |   3 |   0 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    0 |    0 |    0 |    0 |
| CO3            | K3 |   2 |   2 |   3 |   0 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    0 |    1 |    0 |    0 |
| CO4            | K3 |   2 |   2 |   3 |   0 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    0 |    1 |    0 |    0 |
| CO5            | K3 |   2 |   2 |   3 |   0 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    0 |    1 |    0 |    0 |
| CO6            | K3 |   2 |   2 |   3 |   1 |   0 |   0 |   0 |   2 |   3 |    3 |    0 |    3 |    1 |    1 |    0 |
| Score          |    |  12 |  12 |  18 |   1 |   0 |   0 |   3 |   2 |   3 |    3 |    0 |    3 |    4 |    1 |    0 |
| Course Mapping |    |   2 |   2 |   3 |   0 |  0  |   0 |   1 |   0 |   1 |    1 |    0 |    1 |    1 |    0 |    0 |

** COURSE OBJECTIVES
- To understand different client and server end technologies
- To develop web application using traditional technologies
- To understand and develop web applications using emerging web
  application frameworks.

{{{unit}}}
|UNIT I | WEB ESSENTIALS | 9 |
Web Essentials: Clients -- Servers -- Communication; HTTP protocol: Request and Response Messages – Functionalities of Web Client and Web Server; Web Server: Vulnerabilities – Attacks & its prevention; HTML5: Table -- List – Image -- Form -- Semantic elements -- CSS3: Types of style sheets – Selectors – Box Model -- Rule cascading -- Inheritance -- Transformations --Transitions -- Animations

#+BEGIN_COMMENT
17th March 2021
Addition    
  CSS Box as it is fundamental
Removal
  Audio and video controls as they are not very important
#+END_COMMENT

{{{unit}}}
|UNIT II | CLIENT SIDE PROGRAMMING | 9 |
JavaScript: Variables – Data types -- Statements – Function -- Object -- Array -- Built-in objects (String and Date) --  JSON: Parse, Stringify -- Event handling: Form, Mouse and Keyboard events -- DOM: Document tree –  Node object – Document object -- Event handling: Event propagation

#+BEGIN_COMMENT
Removal
   Contents related to JSON in AU R-2017 has been removed
Thought Process
   Due to time constraint
   JSON is a structure used for tranferring data in web applications. Since it will not be explicitly  utilized for transfer in the development of web applications, it has been removed.   
   
   17th March 2021
   JSON and its important methods are added because JSON is used recently instead of XML
   Keyboard events are added specifically, as now the trend is to use mobile where we will have to use keyboard only
#+END_COMMENT

{{{unit}}}
|UNIT III | SERVER SIDE PROGRAMMING| 9 |
Servlets: Architecture -- Life Cycle -- Parameter data -- Sessions --
Cookies and URL rewriting -- AJAX: Ajax Client Server Architecture --
XML Http Request Object -- Call Back Methods

#+BEGIN_COMMENT
Removal
    Contents related to JSP in AU R-2017 have been removed      
Thought Process
    Both servlet and JSP are serverside scripting languages
    Since Servlet itself is enough for the students to undertand the configuration of web applications, JSP has been removed
#+END_COMMENT

{{{unit}}}
|UNIT IV | CLIENT SIDE FRAMEWORK | 9 |
Javascript for ReactJS –- React elements – ReactDOM –- React Components – Mapping Arrays with JSX – Create React App – useState Hook: Refactoring for Advanced Reusability – useEffect Hook: State in component tree, Dependency Array – Rules to follow with hooks -- React router: Incorporation –-Nesting – Parameters

#+BEGIN_COMMENT

Removal
      PHP and XML in AU R-2017 have been removed
Thought Process
      PHP is yet another serverside scripting language
      XML is a structure used for tranferring data in web applications. Since it will not be explicitly being utilized for trasnfer in the development of web applications       

Inclusion
      Concepts related to ReactJS have been included
Thought process
      It is a recently developed lightweight client side framework useful for quick development of web application
17th March 2021
Change
Topics are changed based on the following book as the React moved to recent version
https://www.oreilly.com/library/view/learning-react-2nd/9781492051718/
From the above link, we have taken the recent concepts
#+END_COMMENT

{{{unit}}}
|UNIT V | SERVER SIDE FRAMEWORK | 9 |
Node building blocks: Global objects, Events, Asynchronous Nature – Node and the Web: Server and Client  – Build and the NodeJS using MVC: Routing, Creation of Modules, Views and Controllers

#+BEGIN_COMMENT
Removal
      AJAX and Web services in AU R-2017 have been removed
Thought Process
      AJAX has been moved to Unit 3
      Time constraint
      Web services in a way is not much relevant with the development of web applications
      Having understood the basics of web application development, one can futher explore how web services can be used in the development of web application in future relatively better
Inclusion
      Concepts related to NodeJS have been included
Thought process
      It is a recently developed lightweight sever side framework useful for quick development of web applications
17th Marsh 2021
Node building blocks – Learning node 2nd edition
Introducing NPM, Javascript Package Manager  -- Your first week with NodeJS
https://www.oreilly.com/library/view/learning-react-2nd/9781492051718/
Node and the Web - Learning node 2nd edition
https://www.oreilly.com/library/view/learning-node-2nd/9781491943113/
Build and the NodeJS using MVC - Your first week with NodeJS

#+END_COMMENT

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Make use of HTML5 and CSS3 to design modern web site  (K3)
- Utilize Javascript and DOM to implement dynamic web page (K3)
- Develop responsive web applications using Servlets and AJAX (K3)
- Build web application using ReactJS framework (K3)
- Develop web application using NodeJS framework (K3).
- •	Examine various technologies to design web application with best practices  in teams with clear documentation (K4).
      
** TEXT BOOKS
1. Jeffrey C, Jackson, ``Web Technologies A Computer Science
   Perspective'', Pearson Education, 2011. (Units 1,2,3)
2. Alex Banks, Eve Porcello, ``Learning React: Modern 
   Patterns for Devloping React Apps'', June 2020, O'Reilly Media Inc.,
   (Unit 4)

** REFERENCE BOOKS
1. David McFarland, ``CSS3: The missing manual'', O'Reilly Media,
   December 2012. (Unit 1)
2. Matthew MacDonald, ``HTML5: The missing manual'', O'Reilly Media,
   August 2011 (Unit 1)
3. Shelly Powers, ``Learning Node 2nd Edition'', 1st
   Edition, O'Reilly Media, June 2016. (Unit 5)
4. Sitepoint Team, ``Your First Week With Node.js'', SitePoint, February 2018. (Unit 5)
5. ''How to Hack a Web Server'',
   https://www.guru99.com/how-to-hack-web-server.html (Unit 1)
