**  <<<PE405>>> SOFT COMPUTING
:properties:
:author: Dr. T.T. Mirnalinee  and Dr. K. Lekshmi
:date: 25/03/2021
:end:

#+begin_comment
- 1. One professional elective is offered by the same name in AU 2017
- 2. Referred other university syllabus.
- 3. Offered only in AU BE 2017 curriculum
- 4. Five Course outcomes specified and aligned with units
- 5. Not Applicable.
#+end_comment

#+startup: showall


** CO PO MAPPING :noexport:
#+NAME: co-po-mapping
|                |    | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 | PSO1 | PSO2 | PSO3 |
|                |    |  K3 |  K4 |  K5 |  K5 |  K6 |   - |   - |   - |   - |    - |    - |    - |   K5 |   K3 |   K6 |
| CO1            | K2 |   2 |   2 |   1 |   1 |   1 |   0 |   0 |   1 |   1 |    1 |    0 |    1 |    1 |    2 |    1 |
| CO2            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   1 |   1 |    1 |    0 |    1 |    2 |    3 |    1 |
| CO3            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   1 |   1 |    1 |    0 |    1 |    2 |    3 |    1 |
| CO4            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   1 |   1 |    1 |    0 |    1 |    2 |    3 |    1 |
| CO5            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   1 |   1 |    1 |    0 |    1 |    2 |    3 |    1 |
| CO6            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   1 |   1 |    1 |    0 |    1 |    2 |    3 |    1 |
| Score          |    |  14 |  10 |   9 |   9 |   5 |   0 |   0 |   5 |   5 |    5 |    0 |    5 |    9 |   14 |    5 |
| Course Mapping |    |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   1 |   1 |    1 |    0 |    1 |    2 |    3 |    1 |




{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To introduce the ideas of fuzzy sets and fuzzy logic 
- To study the characteristics of various types of neural networks.
- To gain insight in Hybrid Learning Models . 
- To  provide  the  mathematical  background  for  carrying  out  the  optimization  associated  with neural network learning and genetic algorithms.
- To  introduce  case studies  utilizing the  above and  illustrate the intelligent behavior of programs based on soft computing

{{{unit}}}
| UNIT I | INTRODUCTION TO SOFT COMPUTING | 8 |
Introduction: Neural networks -- Fuzzy logic -- Genetic algorithm --
Hybrid systems; Artificial Neural Network: Fundamental concepts --
Evolution of neural networks -- Basic modals of ANN -- McCulloch and
Pitts neuron -- Linear separability -- Hebb network.
#+begin_comment
Almost same, but removed Hebbian  and  Delta-Perceptron Network-Adaline Network-Madaline Network from AU syllabus
#+end_comment

{{{unit}}}
| UNIT II | SUPERVISED, UNSUPERVISED, AND ASSOCIATIVE LEARNING NETWORKS | 11 |
Supervised Learning Network: Perceptron networks -- Adaptive linear
neuron -- Multiple adaptive linear neurons -- Back propagation
networks -- Radial bias function network; Associative Memory Networks:
Autoassociative memory network -- Bidirectional associative memory --
Hopfield networks; Unspervised Learning Networks: Hamming network --
Kohonen neural network -- Learning vector quantization -- Adaptive
resonance theory networks.
#+begin_comment
Removed Spike Neuron Models from AU syllabus
Organised as per supervised, unsupervised learning techniques
#+end_comment

{{{unit}}}
| UNIT III | FUZZY SYSTEMS | 9 |
Introduction to fuzzy logic -- Classical sets -- Fuzzy sets -- Fuzzy
relations -- Membership functions -- Defuzzification methods -- Fuzzy
arithmetic -- Fuzzy measures -- Fuzzy rule base and approximate
reasoning -- Fuzzy decision making.

#+startup: showall

{{{unit}}}
|UNIT I | Fuzzy Set Theory | 9 |
Introduction to Neuro, Fuzzy and Soft Computing; Fuzzy Sets : Basic Definition and Terminology --
Set-theoretic Operations -- Member Function Formulation and Parameterization -- Fuzzy Rules and Fuzzy Reasoning --
Extension Principle and Fuzzy Relations -- Fuzzy If-Then Rules -- Fuzzy Reasoning -- Fuzzy Inference Systems 
-- Mamdani Fuzzy Models -- Sugeno Fuzzy Models --Tsukamoto Fuzzy Models -- Input Space Partitioning and Fuzzy Modeling.

{{{unit}}}
|UNIT II | Neural Networks | 9 | 
Supervised Learning Neural Networks: Perceptrons –- Adaline –- Backpropagation Mutilayer Perceptrons –- Radial Basis Function Networks;
Unsupervised Learning NeuralNetworks: Competitive Learning Networks –- Kohonen Self-Organizing Networks -– Learning Vector Quantization –- Hebbian Learning.

{{{unit}}}
|UNIT III | Neuro Fuzzy Modeling | 9 |
Adaptive Neuro-Fuzzy Inference Systems: Architecture –- Hybrid Learning Algorithm –- Learning Methods that Cross-fertilize ANFIS and RBFN; 
Coactive Neuro Fuzzy Modeling: Framework Neuron Functions for Adaptive Networks –- Neuro Fuzzy Spectrum.

{{{unit}}}
|UNIT IV | Optimization | 9 |
Derivative-based Optimization: Descent Methods -- The Method of Steepest Descent -- Classical Newton's Method -- Step Size Determination 
-- Derivative-free Optimization; Genetic Algorithms: Simulated Annealing -- Random Search -- Downhill Simplex Search -- Particle Swarm Optimization 
-- Ant Colony Optimization.

{{{unit}}}
|UNIT V | Applications of Computational Intelligence | 9 | 
Fraud Detection in Healthcare: Definition and Types of Healthcare Fraud -- Identifying Healthcare Fraud from Data -- 
Knowledge Discovery-Based Solutions for Identifying Fraud; Data Analytics for Pharmaceutical Discoveries: Introduction -- Chemical and Biological Data -- 
Spontaneous Reporting Systems (SRSs); Clinical Decision Support Systems: Various Types of CDSS, Diagnostic Decision Support.

Shortest Path Algorithm; Printed Character Recognition; Inverse Kinematics Problems; Automobile Fuel Efficiency Prediction;
Soft Computing for Color Recipe Prediction; Stock Marker Forecasting


\hfill *Total Periods: 45*

#+begin_comment
** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Use fuzzy logic (K3).
- Design of various neural networks (K3).
- Apply optimization in neural networks and genetic programming (K3).
- Discuss hybrid soft computing (K2).
- Apply various soft computing frame works on different case studies (K3).
- Develop intelligent modeling, optimization and control of non-linear systems (K3).

#+end_comment

** TEXT BOOKS
1.	J.S.R.Jang, C.T. Sun and E.Mizutani, ``Neuro-Fuzzy and Soft Computing'', PHI / Pearson Education 2004. 


REFERENCE BOOKS
1.	S.Rajasekaran and G.A.Vijayalakshmi Pai, ``Neural Networks, Fuzzy Logic and Genetic Algorithm: Synthesis & Applications'', Prentice-Hall of India Pvt. Ltd., 2006. 
2.	Timothy J.Ross, ``Fuzzy Logic with Engineering Applications'', McGraw-Hill, International Editions, Electrical Engineering Series, Singapore, 1997.
3.	Davis E.Goldberg, ``Genetic Algorithms: Search, Optimization and Machine Learning'', Addison Wesley, N.Y., 1989.
4.	Samir Roy, ``Introduction to Softcomputing : NeuroFuzzy and Genetic Algorithms'', First edition, Pearson Publishers, 2015.
5.	R.Eberhart, P.Simpson and R.Dobbins, ``Computational Intelligence - PC Tools'', AP Professional, Boston. 1996.
6.	Stamatios V. Kartalopoulos, ``Understanding Neural Networks and Fuzzy Logic Basic concepts & Applications'', IEEE Press, PHI, New Delhi, 2004.
7.	Vojislav Keeman, ``Learning & Soft Computing Support Vector Machines, Neural Networks, and Fuzzy Logic Models'', Pearson Education, New Delhi, 2006.
