* <<<PE104>>> STATISTICAL INFERENCE
:properties:
:author: Dr R S Milton
:date: 
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 2 | 0 | 4 |

** COURSE OBJECTIVES
- To identify the standard distributions and apply them in solving problems
- To understand the concept of two-dimensional random variables and solve
  problems in finding the Joint probabilities and correlation between
  them
- To perform hypothesis testing using normal, t-distribution and F-distribution
- To evaluate the tests of significance in analysis of variance
- To calculate the various statistical quality control measurements.

{{{unit}}}
| UNIT I | PROBABILITY | 12 |
Probability -- Random variables -- Expectation -- Convergence
of random variables. 

{{{unit}}}
| UNIT II | INFERENCE | 12 |
Models, Statistical Inference and Learning -- Estimating the
cdf and Statistical Functionals -- Bootstrap -- Parametric
inference. 

{{{unit}}}
| UNIT III | HYPOTHESIS TESTING | 12 |
Hypothesis testing and p-values -- Bayesian inference --
Statistical decision theory 

{{{unit}}}
| UNIT IV | STATISTICAL MODELS AND METHODS | 12 |
Linear and logistic regression -- Multivariate models --
Inference about independence -- Causal inference

{{{unit}}}
| UNIT V | ESTIMATION STATISTICS | 12 |
Directed graphs and conditional independence -- Undirected
graphs -- Log-linear models -- Classification
\hfill *Total Periods: 60*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Identify standard distributions and apply them
- Solve problems in two dimension random variables and find the
  correlation between them
- Identify and apply the suitable testing of hypothesis under normal
  and t and F distribution
- Solve problems in analysis of variance
- Analyze quality control by applying control chart methods.
      
** TEXT BOOKS
1. Milton J S and Arnold J C, ``Introduction to Probability and
   Statistics'', 4th Edition, 3rd Reprint, Tata McGrawHill, 2008.
2. Johnson R A and Gupta C B, ``Miller and Freund's Probability and
   Statistics for Engineers'', 8th Edition, Pearson Education, 2011.

** REFERENCES
1. Devore J L, ``Probability and Statistics for Engineering and the
   Sciences'', 7th Edition, ThomsonBrooks/Cole, International Student Edition, 2008.
2. Walpole R E, Myers R H, Myers S L, Ye K, ``Probability
   and Statistics for Engineers and Scientists'', 8th Edition, Pearson Education,
   Asia, 2007.
3. Ross S M, ``Introduction to Probability and Statistics for
   Engineers and Scientists'', 3rd Edition,  Elsevier, 2004.
4. Spiegel M R, Schiller J, Srinivasan R A, ``Schaum’s
   Outline of Theory and Problems of Probability and Statistics'',
   Tata McGraw Hill, 2004.
5. Gupta S C, Kapoor V K, ``Fundamentals of Mathematical
   Statistics'', Sultan and Chand Company, 2009.
