* <<<PE102>>> SOFTWARE TESTING
:properties:
:author: Dr. K. Madheswari and Dr. A. Chamundeswari
:date:16.03.2021
:end:

#+startup: showall
** CO PO MAPPING :noexport:
#+NAME: co-po-mapping
|                |    | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 | PSO1 | PSO2 | PSO3 |
|                |    |  K3 |  K4 |  K5 |  K5 |  K6 |   - |   - |   - |   - |    - |    - |    - |   K5 |   K3 |   K6 |
| CO1            | K2 |   2 |   2 |   1 |   1 |   1 |   1 |   0 |   1 |   1 |    0 |    1 |    1 |    1 |    2 |    1 |
| CO2            | K3 |   3 |   2 |   2 |   2 |   1 |   1 |   0 |   1 |   1 |    0 |    1 |    1 |    2 |    3 |    1 |
| CO3            | K3 |   3 |   2 |   2 |   2 |   1 |   1 |   0 |   1 |   1 |    0 |    1 |    1 |    2 |    3 |    1 |
| CO4            | K3 |   3 |   2 |   2 |   2 |   1 |   1 |   0 |   1 |   1 |    0 |    1 |    1 |    2 |    3 |    1 |
| CO5            | K3 |   3 |   2 |   2 |   2 |   1 |   1 |   0 |   1 |   1 |    0 |    1 |    1 |    2 |    3 |    1 |
| Score          |    |  14 |  10 |   9 |   9 |   5 |   5 |   0 |   5 |   5 |    0 |    5 |    5 |    9 |   14 |    5 |
| Course Mapping |    |   3 |   2 |   2 |   2 |   1 |   1 |   0 |   1 |   1 |    0 |    1 |    1 |    2 |    3 |    1 |


{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |
#+begin_comment

1.Anna University Regulation 2017 has this course. 
2.The syllabus content across units were modified in Autonomous syllabus as adviced by the domain expert committee.Unit V(SOFTWARE QUALITY ASSURANCE) has been newly introduced.
3.Not Applicable
4. Five Course outcomes specified and aligned with units
5.Not Applicable
#+end_comment

** Course Objectives
- To learn the software testing fundamentals 
- To acquire structural and analtical testing knowledge in  software code
- To understand and apply the levels of testing 
- To apply quality testing and tools in software projects 
- To apply testing concepts in web and mobile applications.

{{{unit}}}
|UNIT I| TESTING FUNDAMENTALS |9| 
Testing activities in software life cycle, Readiness of a Product: dependability, availability, MTBF, reliability, alpha test, beta test ,
regression test; Validation and Verification; Basic Principles; Test and Analysis Activities Within a Software Process: The Quality
Process, Planning and Monitoring, Quality Goals, Dependability Properties, Analysis, Testing, Improving the Process; Finite Models, Control Flow Graphs, Call
Graphs, Finite State Machines.

#+begin_comment
 Text Book 2 Chapter 1, 2 
#+end_comment

{{{unit}}}
|UNIT II| STRUCTURED AND ANALYTICAL TESTING  |9| 
Structure Based testing : Introduction - - condition coverage -- decision - - modified --  multiple-- path testing -- APT testing -- exercises;  Analytical testing :  static analysis --  Dynamic analysis -- samples ;

#+begin_comment
Text Book 1, chapter 2,3
#+end_comment
{{{unit}}}

|UNIT III| QUALITY TESTING AND TOOLS |9| 
Quality Characteristics for technical testing :  Security -- reliability -- efficiency -- changeability --testability -- portability - installability -- sample questions; Test tools and Automation : Test automation project -- specific test tools -- sample exam ;

#+begin_comment
Text Book 1, chapter 4,6
#+end_comment
{{{unit}}}

|UNIT IV| TESTING OBJECT-ORIENTED SOFTWARE |9|
Testing Object-Oriented Software: Issues in Testing Object-Oriented Software, An Orthogonal Approach to Test, Intraclass Testing, Testing with State Machine Models, Interclass Testing, Structural Testing of Classes, Oracles for Classes, Polymorphism and Dynamic Binding, Inheritance, Genericity, Exceptions; Fault-Based Testing: Assumptions, Mutation Analysis, Fault-Based Adequacy Criteria. 

#+begin_comment
 Text Book 2, chapter 15, 16  
#+end_comment 

{{{unit}}}

|UNIT V|WEB AND MOBILE APPLICATION TESTING   |9|
Website Testing ;Challenges in mobile testing ; Testing Mobile Apps: Mobile specific testing--functional Testing-- Usability testing--Accessibility testing--Stress and Interrupt testing--performance testing--security testing; Mobile Test automation Tools: image recognition--OCR/text recognition-- Native object recognition--current state of tools; Mobile cloud testing.

#+begin_comment
Text Book 3, chapter 3,4,5,6,14
\hfill *Total: 45*

** COURSE OUTCOMES
Upon the completion of the course the students should be able to: 
- Summarize software testing practices (K2)
- Experiment  structural and analytical testing (K3)
- Apply quality testing and tools in projects  (K3)
- Build OO software and test (K3)
- Apply testing concepts in web and mobile applications   (K3)>

** TEXT BOOKS
1) Jamie L. Mitchell, Rex Black, Advanced software testing: Guide to the ISTQB Advanced Certification as an Advanced Technical test Analyst, Second  edition, Vol 3, 2015.(Unit 2, 3)(chapter 1,2 4,6)
2 ) Mauro Pezze , Michal Young, Software Testing and Analysis(unit 1,4 (chapte1,2,15.16))
Process, Principles, and Techniques, Wiley publications 2007.(unit 1,4)
3) Daniel Knott, "Hands-On Mobile App Testing", Addison- Wesley, 2015.(unit 5)

** REFERENCES
1. Aditya Mathur, ``Foundations of Software Testing'', Pearson
   Education, 2008.
2. Ron Patton, ``Software Testing'', 2nd Edition, Pearson    Education, 2007.
3. Robert Furtell, Donald Shafer, and Linda Shafer, ``Quality Software    Project Management'', Pearson Education Asia, 2002.

