* <<<PE101>>> BIG DATA TECHNOLOGIES
:properties:
:author: Dr. J Suresh and Dr. Y. V. Lokeswari
:date: 26-03-2021
:end:


#+begin_comment

#+end_comment

#+startup: showall
** CO PO MAPPING :noexport:
#+NAME: co-po-mapping
|                |    | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 | PSO1 | PSO2 | PSO3 |
|                |    |  K3 |  K4 |  K5 |  K5 |  K6 |   - |   - |   - |   - |    - |    - |    - |   K5 |   K3 |   K6 |
| CO1            | K2 |   2 |   1 |   1 |   1 |   1 |   0 |   0 |   0 |   0 |    0 |    0 |    1 |    1 |    2 |    1 |
| CO2            | K3 |   3 |   2 |   2 |   2 |   1 |   1 |   0 |   1 |   1 |    0 |    0 |    2 |    2 |    3 |    1 |
| CO3            | K3 |   3 |   2 |   2 |   2 |   1 |   1 |   0 |   1 |   1 |    1 |    0 |    2 |    2 |    3 |    1 |
| CO4            | K3 |   3 |   2 |   2 |   2 |   1 |   1 |   0 |   1 |   1 |    1 |    0 |    2 |    2 |    3 |    1 |
| CO5            | K3 |   3 |   2 |   2 |   2 |   1 |   1 |   0 |   1 |   1 |    1 |    0 |    2 |    2 |    3 |    1 |
| Score          |    |  14 |   9 |   9 |   9 |   5 |   4 |   0 |   4 |   4 |    3 |    0 |    9 |    9 |   14 |    5 |
| Course Mapping |    |   3 |   2 |   2 |   2 |   1 |   1 |   0 |   1 |   1 |    1 |    0 |    2 |    2 |    3 |    1 |


{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** Course Objectives
- To understand the competitive advantages of big data technologies
- To understand distributed data processing using Hadoop MapReduce and Spark
- To learn apache spark for stream processing
- To learn apacke kafka for building distributed data applications.
- To understand various big data frameworks.


{{{unit}}}
|Unit I|Introduction to Big Data Technologoy|5| 
Introduction -- Understanding Big Data --  Big Data: Benifitting -- Managing -- Organizing and Analyzing Big Data: Learning and Analytics; Technology Challenges for Big Data.

{{{unit}}}
|Unit II| Big Data Processing |10| 
Introduction -- Distributed File System -- HDFS Design Goals -- MapReduce Overview -- Writing and Testing MapReduce Programs -- Installing Spark and Setting up Spark Cluster -- Spark Shell -- Creating Spark Session Object -- Resilient Distributed Datasets (RDD) -- Manipulating RDD -- NoSQL -- SparkSQL -- GraphX.

{{{unit}}}
|Unit III|Stream Processing |10| 
Stream Processing Concepts -- Distributed Stream Processing -- Stream Processing Model -- Streaming Architecture -- Lambad and Kappa Architecture -- Struecture streaming -- Spark Streaming -- Spark Streaming Programming Model -- Other Distributed Real Time Stream Processing Systems.

{{{unit}}}
|Unit IV| Streaming Processing using Kafka |10|
Apache Kafka -- Installing Kafka -- Producers and Consumers -- Kafka Internals -- Building Data Pipelines -- Cross Cluster Data Mirroring -- Administering and Monitoring Kafka -- Getting started with Kafka Streams -- Kafka Streams Development -- Applications with Kafka Streams.

{{{unit}}}
|Unit V|Big Data Frameworks |10|
Apache Flume -- Overview and Architecture -- Quick Start Guide to Flume -- Basics of Sqoop -- Integrating Sqoop with Hadoop -- Getting to Grips with Zookeeper -- Getting Started with Zookeepre API --  Machine Learning using Apache Mahout -- Clustering & Classification Algorithms in Mahout --  Extending Spark with H20 -- H2O

** Course Outcomes
Upon the completion of the course the students should be able to: 
- Illustrate big data analytics and related technologies (K2)
- As a team build distributed data processing applicatins using Apache Hadoop and communicate the results   (K3)
- Develop distributed data processing applications using Apache Spark by using open source platform practices (K3)
- As a team build a model using Apache Kafka for processing stream data (K3)
- Develop a simple applications suitable for society using Big Data Frameworks (K3)

** Text Books
1. Mike Frampton, "Mastering Apache Spark", Packt Publishers, 2015.(U2)
2. Krishna Sankar, " Fast Data Processing using Spark 2", 3rd Edition, Packt Publishers, 2016. (u2)
3. Neha Narkhede, Gwen Shapira, and Todd Palino,"Kafka - Definitive Guide", 2017.(U4)

** References
1. Gerald Maas & Francois Gorillot, "Stream Processing with Apache Spark", O'Reilly Media, 2019.(U3)
2. Gaurav Vaish, "Getting Started with NoSQL",  Packt Publishing Ltd, 2013.
3. William P. Bejeck Jr. "Kafka Streams in Action", Manning Publications, 2018.
4. Jayani Withanawasam, "Apache Mahout Essentials", Packt Publishers, 2015 (u5)
5. Steve Hoffman, "Apache Flume: Distributed Log Collection for Hadoop", 2nd Edition, Packt Publishers, 2015 (u5)
6. Flavio Junqueira, Benjamin Reed, "ZooKeeper: Distributed Process Co-ordination Paperback", O'Reilly Media, 2014 (u5)
7. Kathleen Ting, Jarek Jarcec Cecho, "Apache Sqoop Cookbook: Unlocking Hadoop for Your Relational Database", O'Reilly Media, 2013.


