* <<<PE202>>> BIG DATA MANAGEMENT
:properties:
:author: Dr. J Suresh and Dr. Y. V. Lokeswari
:date: 26-03-2021

#+begin_comment
- 1. 3 units are the same as AU
- 2. For changes, see the individual units. Unit - III of AU 2017 syllabus is removed. Unit IV is added as new
- 3. There are difference in three units when compared to M.E
- 4. Five Course outcomes specified and aligned with units
- 5. Not Applicable
#+end_comment

#+startup: showall
** CO PO MAPPING :noexport:
#+NAME: co-po-mapping
|                |    | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 | PSO1 | PSO2 | PSO3 |
|                |    |  K3 |  K4 |  K5 |  K5 |  K6 |   - |   - |   - |   - |    - |    - |    - |   K5 |   K3 |   K6 |
| CO1            | K2 |   2 |   2 |   1 |   1 |   1 |   0 |   0 |   0 |   1 |    0 |    0 |    1 |    1 |    2 |    1 |
| CO2            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   0 |   1 |    0 |    0 |    1 |    2 |    3 |    1 |
| CO3            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   1 |   1 |    1 |    1 |    2 |    2 |    3 |    1 |
| CO4            | K3 |   3 |   3 |   2 |   2 |   1 |   0 |   0 |   1 |   2 |    1 |    1 |    3 |    2 |    3 |    1 |
| CO5            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   1 |   3 |    3 |    2 |    3 |    2 |    3 |    1 |
| Score          |    |  14 |  13 |   9 |   9 |   5 |   0 |   0 |   3 |   8 |    5 |    4 |   10 |    9 |   14 |    5 |
| Course Mapping |    |   3 |   3 |   2 |   2 |   1 |   0 |   0 |   1 |   2 |    1 |    1 |    2 |    2 |    3 |    1 |

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To know the fundamental concepts of big data and analytics
- To understand the basics of data modeling and its implications 
- To learn different data models adopted in big data 
- To get introduced to big data management system and its variable technologies
- To learn various tools supporting big data management system.

{{{unit}}}
| UNIT I | Introduction to Big Data Model | 5 |
Concept of Big Data -- Sources and types of big data -- Data Ingestion -- Data Storage -- Data Quality -- Data Operations -- Data Scalability and Security -- Data Managment in Energy, Gaming and Flight Operations.

{{{unit}}}
| UNIT II | Data Repository and Storage Format | 10 |
Introduction to Big Data Modeling -- Importance and implications of big data modeling and management -- Big data storage and data models -- Data model Structures and Operations -- Data Model Constraints -- Relational and Semistructured Data Model -- CSV and JSON data -- Array Data Model. 

{{{unit}}}
|UNIT III |  Data Models for Data Lake | 10 |
Data Models -- Categorizing Data Models -- Data Model vs Data Format -- Data Stream -- Understanding Data Lake -- Inside Data Lake -- Generic Structure of Data Ponds -- Applications of Data Pond -- Data Warehousing vs Data Lake.

{{{unit}}}
|UNIT IV | Key-Value store and Graph databases   | 10 |
Approaches to Big Data -- DBMS and non-DBMS -- DBMS to BDMS -- Introduction to NoSQL  -- Key Value Store: Redis -- Graph Databases An Overview -- Started with Neo4j -- Modelling data for Neo4j -- Use Case Examples: Recommender Systems & Impact Analysis and Simulation -- Visualization for Neo4j.

{{{unit}}}
| UNIT V | Document based and Columnar Models | 10 |
Database for modern Web:MongoDB -- MongoDB Shell -- Creating, Updating and Deleting Documents -- Querying --  Introduction to Cassandra -- Architecture --- CassendraQL (CQL) -- Configuring and Managing a Cluster – Integrating with Apache Spark. 

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Illustrate the different data elements and able to identify data operations needed for problems (K2)
- Explain the needs of differnet data models for desiging big data information system (K3)
- Build a data model to suit the characteristics of data using Data lake in teams (K3) 
- Compare between a traditional DBMS and BDMS and apply it for building a system for managing big data in teams. (K3)
- Design and build a new information system using BDMS tools in teams, demostrate and write report on the work. (K3) 
  
** TEXT BOOKS
1. James Lee , Tao Wei , Suresh Kumar Mukhiya, "Hands-On Big Data Modeling", Packt Publishers, 2018.(u1 & u2)
2. Bill Inmon, "Data Lake Architecture: Designing the data lake and avoiding the garbage dump", 1st Edition, Technics Publications, 2016.(u3)
3. Shannon Bradshaw, Eoin Brazil, Kristina Chodorow, "MongoDB: The Definitive Guide", 3rd Edition, 2019.(u4)

** REFERENCES
1. Kim H Pries, Robert Dunnigan, "Big Data Analytics: A Practical Guide for Managers", CRC Press, 2015.
2. Vinoo Das, "Learning Redis", Packt Publications, 2015.(u4)
3. Jerome Baton; Rik Van Bruggen, "Learning Neo4j 3.x", 2nd Edition, Packt Publishers, 2017.(u4)
4. Aaron Ploetz , Tejaswi Malepati , Nishant Neeraj, "Mastering Apache Cassandra 3.x", 3rd Edition, Packt Publishers, 2018.(u5)
5. Kyle Banker, Peter Bakkum, Shaun Verch, Douglas Garrett, and Tim Hawkin, "MongoDB in Action", 2nd Edition, Manning Publications, 2016.(u5)
