* <<<PE203>>> SOFTWARE CONFIGURATION MANAGEMENT
:properties:
:author: Dr. K. Vallidevi and Dr. A. Chamundeswari
:date: 14-03-2021
:end:

#+begin_comment
Included project model in Unit I instead of having it in AU R2017 -Unit II
Included scheduling in Unit II instead of having it in AU R2017-Unit III
Added security topic in syllabus, which is not provided in AU R2017
Added risk in Unit IV instead of AU R2017-Unit III
New process model is added in syllabus which is not provided in AU R2017
Included monitoring topics in Unit V instead of AU-Unit IV
#+end_comment

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To learn the key aspects of managerial process in software
  organization.
- To apply the practices followed in project planning, estimation, and
  scheduling
- To be familiar with the overall project activities in Agile and
  DevOps
- To study the various issues in people management
- To distinguish between security and risk activities related with
  software development.

{{{unit}}}
|UNIT I | TRADITIONAL | 9 |
Configuration management process : monitoring and control -- auditing -- testing -- incident and defect management -- problem management -- change management -- automation and tools -- lifecycle controls -- culture and organisation; Service asset and configuration management visions and strategies; Populating a CMDB  Process design : -- populate your CMDB; Case study monolithic application : Build the application -- Deploy the application.

#+begin_comment
...Included from Text book (1), chapter 6,8,10  
...Included from Text book (2) chapter 11
#+end_comment

{{{unit}}}
|UNIT II | MICROSERVICES | 9 |
An Introduction to Microservices:What Are Microservices? ; Switching to Microservices:Cost Components; Interprocess Communication:Putting It All Together; Case Study: Migration to Microservices--Planning for Migration--Planning for Migration--Applying Microservices Criteria --Converting to Microservices--Application Build and Deployment.

#+begin _comment
...Included from Book 2, chapter 1,2,3,12
#+end_comment

{{{unit}}}
|UNIT III | CONTAINERS | 9 |
Docker Containers:Virtual Machines -- Containers -- Docker Architecture and Components -- The Power of Docker: A Simple Example;
Docker Interface:Key Docker Commands -- Dockerfile -- Docker Compose; Case Study: Containerizing a
Helpdesk Application : Containerizing Microservices -- Deploying the Catalog Microservice.

#+begin _comment
...Included from Book 2, chapter 5.7.13
#+end_comment

{{{unit}}}
|UNIT IV | NETWORKING AND DISCOVERY | 9 |




#+begin _comment
...Included from Book (2) chapter 8,9
#+end_comment

{{{unit}}}
|UNIT V | ORCHESTRATION AND SECURITY | 9 |
Visualizing Progress: Relationship between people and effort -- Task
set and network -- Earned value analysis -- SCM -- Managing contracts
-- Working in teams -- Developing metrics on a software development
program -- Evaluating performance.

#+begin _comment
...Included monitoring topics in Unit V instead of AU-Unit IV...
#+end_comment

** COURSE OUTCOMES
Upon completion of the course, the student should be able to:
- Select a process model for software development (K2)
- Estimate cost to manage the software development (K3)
- Develop a project using agile and devops software development
  practices (K3)
- Identify the activities of security and risk in various types of
  software projects (K1)
- Recognize management skills and techniques to develop commercial
  software projects (K2).
      
** TEXT BOOKS
1. Shirley Lacy and David Norfolk, ``CONFIGURATION MANAGEMENT, Expert guidance for IT service managers and practitioners``, Revised edition,  BCS Learning and Development Ltd,   UK, 2014.
2. Parminder Singh Kocher Boston, Microservices and Containers, Addison-Wesley, 2018.
3. 
** REFERENCES
1.  

