* <<<PE202>>> BIG DATA MANAGEMENT
:properties:
:author: Dr. J Suresh and Dr. Y. V. Lokeswari
:date: 21-03-2021

#+begin_comment
- 1. 3 units are the same as AU
- 2. For changes, see the individual units. Unit - III of AU 2017 syllabus is removed. Unit IV is added as new
- 3. There are difference in three units when compared to M.E
- 4. Five Course outcomes specified and aligned with units
- 5. Not Applicable
#+end_comment

#+startup: showall
** CO PO MAPPING :noexport:
#+NAME: co-po-mapping
|                |    | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 | PSO1 | PSO2 | PSO3 |
|                |    |  K3 |  K4 |  K5 |  K5 |  K6 |   - |   - |   - |   - |    - |    - |    - |   K5 |   K3 |   K6 |
| CO1            | K3 |   3 |   2 |   2 |   0 |   1 |   0 |   0 |   0 |   1 |    0 |    0 |    1 |    2 |    3 |    1 |
| CO2            | K4 |   3 |   3 |   2 |   2 |   2 |   0 |   0 |   0 |   1 |    0 |    0 |    1 |    2 |    3 |    2 |
| CO3            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   0 |   1 |    0 |    0 |    1 |    2 |    3 |    1 |
| CO4            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   0 |   1 |    0 |    0 |    1 |    2 |    3 |    1 |
| CO5            | K2 |   2 |   2 |   1 |   1 |   1 |   0 |   0 |   0 |   1 |    0 |    0 |    1 |    1 |    2 |    1 |
| Score          |    |  14 |  11 |   9 |   7 |   6 |   0 |   0 |   0 |   5 |    0 |    0 |    5 |    9 |   14 |    6 |
| Course Mapping |    |   3 |   3 |   2 |   2 |   2 |   0 |   0 |   0 |   1 |    0 |    0 |    1 |    2 |    3 |    2 |


{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To know the fundamental concepts of big data and analytics
- 


{{{unit}}}
| UNIT I | Introduction to Big Data | 9 |
Concept of Big Data -- Sources and types of big data -- Data Ingestion -- Data Storage -- Data Quality -- Data Operations -- Data Scalability and Security -- Data Managment in Energy, Gaming and Flight Operations.


{{{unit}}}
| UNIT II | Big Data Modeling| 9 |
Introduction to Big Data Modeling -- Importance and implications of big data modeling and management -- Big data storage and data models -- Data model Structures and Operations -- Data Model Constraints -- Relational and Semistructured Data Model -- CSV and JSON data -- Array Data Model. 

{{{unit}}}
|UNIT III | Working With Data Models | 9 |
Data Models -- Categorizing Data Models -- Vector space -- Graph -- Other Data models -- Exploring Gephi.

{{{unit}}}
|UNIT IV | Big Data Management System   | 9 |
Approaches to Big Data -- DBMS and non-DBMS -- DBMS to BDMS -- Redis -- Aerospike -- Semistructured Data -- AsterixDB -- Solr -- Vertica.

{{{unit}}}
| UNIT V | Big Data Management Tools | 9 |
Introduction -- Impala -- Neo4j -- SparkSQL -- Case Studies -- 

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Understand different data elements and able to identify data operations needed for problems (K2)
- Understand the needs of differnet data models for desiging big data information system (K3)
- Select a data model to suit the characteristics of data (K3) 
- Differentiate between a traditional DBMS and BDMS, apply it for building a system for managing big data (K3)
- Design and build a new information system using BDMS tools (K4) 
     
** TEXT BOOKS
1. James Lee , Tao Wei , Suresh Kumar Mukhiya, "Hands-On Big Data Modeling", Packt Publishers, 2018.
2. 


** REFERENCES
1. EMC Education Services, ``Data Science and Big Data Analytics: Discovering, Analyzing, Visualizing and Presenting Data'', Wiley Publishers, 2015. (Unit -II)
2. Bart Baesens, ``Analytics in a Big Data World: The Essential Guide to Data Science and its Applications'', Wiley Publishers, 2015.
3. Kim H Pries, Robert Dunnigan, ``Big Data Analytics: A Practical Guide for Managers'', CRC Press, 2015.
4. Jimmy Lin, Chris Dyer, ``Data-Intensive Text Processing with MapReduce'', Synthesis Lectures on Human Language Technologies, Vol. 3, No. 1, Pages 1-177, Morgan Claypool publishers, 2010.
5. Arshdeep Bahga, Vijay Madisetti, ``Big Data Science & Analytics: A Hands-On Approach'', VPT, 2016.
