* <<<PE203>>> SOFTWARE CONFIGURATION MANAGEMENT
:properties:
:author: Dr. K. Vallidevi and Dr. A. Chamundeswari
:date: 14-03-2021
:end:

#+begin_comment
Included project model in Unit I instead of having it in AU R2017 -Unit II
Included scheduling in Unit II instead of having it in AU R2017-Unit III
Added security topic in syllabus, which is not provided in AU R2017
Added risk in Unit IV instead of AU R2017-Unit III
New process model is added in syllabus which is not provided in AU R2017
Included monitoring topics in Unit V instead of AU-Unit IV
#+end_comment

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To learn the key aspects of managerial process in software
  organization.
- To apply the practices followed in project planning, estimation, and
  scheduling
- To be familiar with the overall project activities in Agile and
  DevOps
- To study the various issues in people management
- To distinguish between security and risk activities related with
  software development.

{{{unit}}}
|UNIT I | Configuration Overview | 9 |
Configuration management process : monitoring and control -- auditing -- testing -- incident and defect management -- problem management -- change management -- automation and tools -- lifecycle controls -- culture and organisation; Service asset and configuration management visions and strategies; Populating a CMDB  Process design : -- populate your CMDB; Case study discussion; Automation approach.


#+begin_comment
...Included project model in Unit I instead of having it in AU-Unit II...
#+end_comment

{{{unit}}}
|UNIT II | Microservices | 9 |
Effort Estimation Techniques: Expert judgement -- FPA -- FP mark II --
COSMIC --  -- Cost estimation; Scheduling: Project schedules
-- Network model -- Identifying critical activities.

#+begin _comment
...Included scheduling in Unit II instead of having it in AU-Unit III...
#+end_comment

{{{unit}}}
|UNIT III | AGILE AND DEVOPS | 9 |
Scrum: Organization -- Estimation -- Planning -- Changes in scrum --
Risk in scrum -- Product backlog -- Sprint backlog -- Release --
Identifying stories and preparing to build;

DevOps: Motivation -- Cloud as a platform -- Operations -- Deployment
pipeline.

#+begin _comment
...New process model is added in syllabus which is not provided in AU...
#+end_comment

{{{unit}}}
|UNIT IV | SECURITY AND RISK MANAGEMENT | 9 |
Cloud Security: Cloud information security objectives -- Cloud
security services -- Secure development practices;

Risk Management: Risk culture -- Risk managementprocess -- Risk
attributes -- Risk identification -- Types of risk analysis --
Responding to risk -- Risk tracking -- Risk models.

#+begin _comment
...Added security topic in syllabus, which is not provided in AU...
...Added risk in Unit IV instead of AU-Unit III...
#+end_comment

{{{unit}}}
|UNIT V | MONITORING AND ORGANIZING TEAMS | 9 |
Visualizing Progress: Relationship between people and effort -- Task
set and network -- Earned value analysis -- SCM -- Managing contracts
-- Working in teams -- Developing metrics on a software development
program -- Evaluating performance.

#+begin _comment
...Included monitoring topics in Unit V instead of AU-Unit IV...
#+end_comment

** COURSE OUTCOMES
Upon completion of the course, the student should be able to:
- Select a process model for software development (K2)
- Estimate cost to manage the software development (K3)
- Develop a project using agile and devops software development
  practices (K3)
- Identify the activities of security and risk in various types of
  software projects (K1)
- Recognize management skills and techniques to develop commercial
  software projects (K2).
      
** TEXT BOOKS
1. Shirley Lacy and David Norfolk, ``CONFIGURATION MANAGEMENT, Expert guidance for IT service managers and practitioners``, Revised edition,  BCS Learning and Development Ltd,   UK, 2014.
2.  
** REFERENCES
1.  

