* <<<PE105>>> LOGIC PROGRAMMING
:properties:
:author: Dr. D. Thenmozhi and Dr. K. Lekshmi
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To understand the foundations of Logic programming
- To learn programming in PROLOG
- To implement informed and uninformed search algorithms in PROLOG
- To implement Expert system shell in PROLOG.

{{{unit}}}
|UNIT I|INTRODUCTION TO LOGIC|10|
Foundations of Propositional Logic: Syntax and semantics -- Semantic
entailment; Normal Forms; Resolution in PL; Horn Logic; Foundations of
First Order Logic: Syntax and semantics; Normal Forms; Undecidability
of Predicate Logic; Resolution in FOL: Unification; Refinements of
resolution: P-resolution -- N-resolution -- Linear resolution -- Unit
resolution -- SLD resolution.


{{{unit}}}
|UNIT II|INTRODUCTION TO LOGIC PROGRAMMING|8|
Foundations: Answer generation; Horn Clause Programs: Semantics of
logic program -- Procedural semantics -- Model-theoretic semantics;
Evaluation Strategies: Swapping lemma -- PROLOG's evaluation strategy
-- DFS -- BFS.

{{{unit}}}
|UNIT III|PROGRAMMING IN PROLOG|9|
Syntax & Semantics of PROLOG -- Programming with relations -- Facts --
Questions -- Variables -- Conjunctions of goals -- Backtracking --
Rules -- Structures -- Recursive programs -- Lists -- Operators -- Arithmetic -- 
Controlling execution -- The cut -- Input output -- Exception handling.

{{{unit}}}
|UNIT IV|PROLOG AND ARTIFICIAL INTELLIGENCE|9|
Data structures -- Eight Queens Problem -- Simulation of Automata; 
Operations on Data Structures: Representing and sorting lists -- Representing sets by binary trees --
Insertion & deletion in binary dictionary -- Displaying trees -- Graphs;  
Problem Solving Strategies in AI: DFS -- BFS -- A* Search; Problem Reduction &
AND/OR Graph: Basic AND/OR search procedure; Game Playing: The minimax principle -- 
The alpha-beta algorithm.

{{{unit}}}
|UNIT V|PROLOG AND EXPERT SYSTEMS|9|
Foundations: Introduction to expert systems -- Features of expert
systems -- Functions of an expert system -- Structure of an expert
system; If-then rules for representing knowledge; Developing a Simple
Shell: Implementation -- Dealing with uncertainty;


\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Apply propositional logic and predicate logic for knowledge representation (K3)
- Apply different types of semantics for logic programming (K3)
- Develop programs in PROLOG (K3)
- Solve AI problems using search algorithms in PROLOG (K3)
- Implement a simple Expert system shell in PROLOG (K3).

** TEXTBOOKS:
1. Uwe Schoning, ``Logic for Computer Scientists'', Birkhauser, 1999
   (Units I, II).
2. Ivan Bratko, ``PROLOG: Programming for Artificial Intelligence'',
   4th Edition, Pearson, 2011 (Units III, IV, V).
   
** REFERENCES:
1. Kees Doets, ``From Logic to Logic Programming'', MIT Press 1994.
2. Patrick Blackburn, Johan Bos, Kristina Streignitz, ``Learn PROLOG
   Now'', College Publications, 2006.
3. Dennis Merritt, ``Building Expert Systems in PROLOG'', Amzi!
   Inc. 2000
4. Helder Coelho, Jose C Cotta, ``PROLOG by Example: How to Learn,
   Teach and Use It'', Springer--Verlag, 2011.
5. W F Clocksin, C S Mellish, ``Programming in PROLOG'',
   Springer-Verlag, 2016.
