* <<<PE205>>> TIME SERIES ANALYSIS AND FORECASTING
:properties:
:author: H.Shahul Hamead and V.S.Felix Enigo
:date: 17-03-2021
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To study the statistical background for forecasting.
- To explore the models for regression analysis and forecasting
- To comprehend the exponential Smoothing Methods
- To learn Autoregressive Integrated Moving Average(Arima) models
- To explore transfer Functions and Intervention Models.

{{{unit}}}
|UNIT I | INTRODUCTION TO FORECASTING | 9 |
Introduction to Forecasting:  The Nature and Uses of Forecasts -- Some Examples of Time Series -- The Forecasting Process -- Data for Forecasting --  Resources for Forecasting -- Statistics Background for Forecasting: Graphical Displays -- Numerical Description of Time Series Data -- Use of Data Transformations and Adjustments -- General Approach to Time Series Modeling and Forecasting -- Evaluating and Monitoring Forecasting Model Performance.

{{{unit}}}
|UNIT II | REGRESSION ANALYSIS AND FORECASTING | 9 |
Least Squares Estimation in Linear Regression Models Expert judgement -- Statistical Inference in Linear Regression -- Prediction of New Observations --
Model Adequacy Checking -- Variable Selection Methods in Regression -- Generalized and Weighted Least Squares -- Regression Models for General Time Series Data --  Econometric Models.

{{{unit}}}
|UNIT III | EXPONENTIAL SMOOTHING METHODS| 9 |
First-Order Exponential Smoothing --  Modeling Time Series Data --  Second-Order Exponential Smoothing  -- Higher-Order Exponential Smoothing --
Forecasting  -- Exponential Smoothing for Seasonal Data -- Exponential Smoothing of Biosurveillance Data -- Exponential Smoothers and Arima Models.

{{{unit}}}
|UNIT IV | ARIMA MODELS | 9 |
Linear Models for Stationary Time Series -- Finite Order Moving Average Processes -- Finite Order Autoregressive Processes --
Mixed Autoregressive–Moving Average Processes -- Nonstationary Processes -- Time Series Model Building -- Forecasting Arima Processes.

{{{unit}}}
|UNIT V | TRANSFER FUNCTIONS AND INTERVENTION MODELS | 9 |
Transfer Function Models -- Transfer Function–Noise Models -- Cross-Correlation Function -- Model Specification  --
Forecasting with Transfer Function–Noise Models --  Intervention Analysis.

** COURSE OUTCOMES
Upon completion of the course, the student should be able to:
- Illustrate the statistical background for forecasting (K2)
- Compare various models for regression analysis and forecasting (K2)
- Apply the exponential Smoothing Methods to time series data (K3)
- Build timeseries Autoregressive Integrated Moving Average(Arima) models (K3)
- Make use of transfer functions in time series modelling (K3).
      
** TEXT BOOKS
1. Douglas C. Montgomery, Cheryl L. Jennings, Murat Kulahci, ``Introduction to Time Series Analysis and Forecasting'',
   2nd Edition, Wiley, 2015.

** REFERENCES
1. Peter J. BrockwellRichard A. Davis, ``Introduction to Time Series and Forecasting'', 2ndh Edition, Springer, 2010.
2. George E. P. Box, Gwilym M. Jenkins, Gregory C. Reinsel, Greta M. Ljung, ''Time Series Analysis: Forecasting and Control'', 5th Edition, Wiley, 2015
3. Robert Yaffee, Monnie McGee, ''An Introduction to Time Series Analysis and Forecasting'', 1st Edition, Elsevier, 2000
4. Aileen Nielsen, ''Practical Time Series Analysis'', O'Reilly , Elsevier, 2019
5. Shmueli, G., and K. C. Lichtendahl, Jr., ''Practical Time Series Forecasting with R: A Hands-On Guide'', Axelrod Schnall Publisher, 2015.
