* <<<PE201>>> CLOUD COMPUTING
:properties:
:author: Dr. N. Sujaudeen and Dr. Y. V. Lokeswari 
:date: 22 Mar 2021.
:author: Ms. Y. V. Lokeswari and Dr. J. Suresh
:date: 28 Mar 2019.
:end:

#+startup: showall
{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** CO PO MAPPING :noexport:
#+NAME: co-po-mapping
|                |    | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 | PSO1 | PSO2 | PSO3 |
|                |    |  K3 |  K4 |  K5 |  K5 |  K6 |   - |   - |   - |   - |    - |    - |    - |   K5 |   K3 |   K6 |
| CO1            | K2 |  2  | 2   | 1   |  0  | 0   | 0   | 0   |  0  | 0   |  0   | 0    | 0    |  1   | 2    | 0    |
| CO2            | K3 |  3  | 2   | 2   |  0  | 1   | 0   |  0  |  0  | 0   |  0   | 0    | 3    |  2   | 3    | 0    |
| CO3            | K3 |  3  | 2   | 2   |  0  | 0   | 0   |  0  |  0  | 0   |  0   | 0    | 0    |  2   | 3    | 0    |
| CO4            | K3 |  3  | 2   | 2   |  1  | 1   | 0   |  0  |  0  | 0   |  0   | 0    | 3    |  2   | 3    | 0    |
| CO5            | K2 |  2  | 2   | 1   |  0  | 0   | 0   | 0   |  0  | 0   |  0   | 0    | 0    |  1   | 2    | 0    |
| CO6            | K4 |  3  | 3   | 2   |  2  | 2   | 0   | 0   |  2  | 3   |  3   | 1    | 3    |  2   | 2    | 2    |
| Score          |    |  16 | 13  | 10  |  3  | 4   | 0   |  0  |  2  | 8   |  3   | 1    | 9    |  10  | 15   | 2    |
| Course Mapping |    |  3  | 3   | 2   |  1  | 1   | 0   |  0  |  1  | 2   |  1   | 1    | 2    |  2   | 3    | 1    |

#+begin_comment
1. This syllabus was not offered under AU-2017 Regulations for UG.
2. Introduces the Deep learning theory to undergraduate students which is recent trend and 
   has its application in different areas.
3. This subject is offered under M.E syllabus with additional unit on Deep learning with Tensorflow. 
   For changes, see the individual units.
4. Five Course outcomes specified and aligned with units.
5. No lab.
#+end_comment
#+begin_comment
- 1. Anna University Regulation 2017 has this course. The syllabus content across units were modified in Autonomous syllabus which was mentioned at the end of every unit.
- 2. For changes, see the individual units.
- 3. Not Applicable
- 4. Five Course outcomes specified and aligned with units
- 5. No Lab
#+end_comment

** COURSE OBJECTIVES
- To interpret the basics of cloud computing.
- To learn about concepts of virtualization and virtualization infrastructure.
- To understand the principles of Cloud Architecture, Design challenges and Infrastructure.
- To explore and experiment various Cloud deployment environments.
- To learn about the security issues in the cloud environment. 

{{{unit}}}
|UNIT I|CLOUD ARCHITECTURE AND MODELS |8| 
Cloud Architecture: System Models for Distributed and Cloud Computing
-- NIST Cloud Computing Reference Architecture -- Cloud Characteristics -- Cloud deployment models -- Cloud service models -- Pros and Cons of Cloud; 

#+begin_comment
Removed the contents here and added in 3rd Unit
Cloud Infrastructure: Architectural
design of compute and storage clouds -- Layered cloud architecture
Development -- Design Challenges -- Inter Cloud Resource Management --
Resource Provisioning and Platform Deployment.
#+end_comment

#+begin_comment

Basic introduction about cloud computing is removed from Anna
University syllabus, as this technology has been used by many people.
#+end_comment

{{{unit}}}
|UNIT II |INTRODUCTION TO VIRTUALIZATION|9| 
Basics of Virtualization -- Virtualization Types -- Implementation Levels of Virtualization -- Virtualization Structures / Tools and Mechanisms -- Virtualization of CPU, Memory, I/O Devices -- Virtual Clusters and Resource management -- Virtualization for Data-Center Automation -- Virtualization Support and Disaster Recovery -- Taxonomy of Virtual Machines -- Create VM Cluster using VMWare or Virtual Box and deploy an application.

#+begin_comment
Altered the topic to remove repetition and give a flow for the topic.
-- Virtual Machine Basics -- Process Virtual Machines -- System
Virtual Machines -- Hypervisor -- Key Concepts -- Virtualization
structure -- Implementation levels of virtualization -- Virtualization
Types: Full Virtualization -- Para Virtualization -- Hardware
Virtulization.

 Create a Cluster of 2 Virtual Machines using VMWare or Virtual Box on top of Windows (64 Bit) as Host Operating System. Configuration as follows: VM1 : Ubuntu 16.04 LTS Server (64 Bit) -- VM2 :  Ubuntu 16.04 Desktop. (64 Bit) -- 	Do the following. -- 1. Install Java using JDK in VM2 and -- 2. Remotely login from VM1 to VM2 (password-less using SSH) and run a Java program to perform file input and output operations.
#+end_comment

#+begin_comment

SOA, webservices and PUb/Sub systems are removed from AU syllabus as
they are covered in Distributed Systems.
#+end_comment

{{{unit}}}
|UNIT III|CLOUD INFRASTRUCTURE|9| 
Cloud Infrastructure: Architectural design of compute and storage clouds -- Layered cloud architecture Development -- Design Challenges -- Inter Cloud Resource Management -- Resource Provisioning and Platform Deployment -- Global Exchange of Cloud Resources.

#+begin_comment
Rearranged the content to get align with II Unit. Also, removed the redundant topics.
Comprehensive Analysis -- Resource Pool -- Testing Environment --
Virtual Workloads -- Provision of Virtual Machines -- Desktop
Virtualization -- Network Virtualization -- Server and Machine
Virtualization -- Storage Virtualization -- System-level of Operating
Virtualization -- Application Virtualization-- Virtualization of CPU,
Memory and I/O devices -- Virtual clusters and Resource Management --
Virtual Machine Monitors: KVM, Xen, VMWareESXi server.
#+end_comment

#+begin_comment

Virtualization technology is detailed in this unit. The topics of
Unit - III as per AU syllabus is moved to Unit I in Autonomus syllabus.
#+end_comment

{{{unit}}}
|UNIT IV| CLOUD DEPLOYMENT ENVIRONMENT|12|
Parallel Programming Framework: Hadoop Map Reduce -- Google App Engine -- Amazon AWS -- Microsoft Azure; Cloud Software Environments -- Eucalyptus -- OpenStack -- OpenNebula -- Aneka -- CloudSim.

#+begin_comment
No Change.
#+end_comment

#+begin_comment

This unit covers programming models which is present as Unit - V in AU
syllabus.
#+end_comment

{{{unit}}}
| UNIT V | CLOUD SECURITY | 7 |
Data Security and Storage; Identity and Access Management(IAM) -- IAM Challenges -- IAM Architecture and Practice; Security Management in the Cloud -- Security Management Standards -- SaaS, Paas and IaaS Availability Management -- Access Control; Security-As-A-Service.

#+begin_comment

No Change.
#+end_comment

#+begin_comment

This unit covers Cloud Security issues which is present as Unit - IV
in AU syllabus.
#+end_comment

\hfill *Total Periods: 45*

** COURSE OUTCOMES
Upon the completion of the course the students should be able to:
- Discuss about the basics of Cloud Computing. (K2)
- Apply the concept of virtualization and analyse its types. (K3)
- Illustrate various design challenges in cloud environment. (K3)
- Develop and deploy services on cloud and be able to set up a private cloud environment using open source software. (K3)
- Understand security challenges in cloud environment. (K2)
- Experiment virtualization in teams and deploy an application on Virtual Machine following legal governance, demonstrate and write report. (K4)


** TEXT BOOKS
1. Kai Hwang, Geoffery C Fox, Jack J Dongarra, ``Distributed and
   Cloud Computing: Clusters, Grids, Clouds and the Future of
   Internet'', 1st Edition, Morgan Kaufman Publisher, Oxford, an Imprint of
   Elsevier, 2012. (Unit I, II, IV)
2. Srinivasan A, Suresh J, ``Cloud Computing: A practical Approach for
   Learning and Implementation'', Pearson Education
   India, 2014. (Units I, II, III, IV)

** REFERENCES
1. Tim Mather, Subra Kumaraswamy, Shahed Latif , ``Cloud Security
   and Privacy: an enterprise perspective on risks and compliance'',
   O'Reilly Media, 2009. (Unit V)
2. Danielle Ruest, Nelson Ruest, ``Virtualization: A Beginner's
   Guide'', McGraw-Hill Osborne Media, 2009.
3. James E Smith, Ravi Nair, ``Virtual Machines: Versatile Platforms
   for Systems and Processes'', Elsevier/Morgan Kaufmann, 2005.
4. William von Hagen, ``Professional Xen Virtualization'', Wrox
   Publications, January, 2008.
5. David Marshall, Wade A Reynolds, ``Advanced Server Virtualization:
   VMware and Microsoft Platform in the Virtual Data Center'',
   Auerbach Publications, 2006.
   
