* <<<PE203>>> SOFTWARE CONFIGURATION MANAGEMENT
:properties:
:author: Dr. K. Vallidevi and Dr. A. Chamundeswari
:date: 14-03-2021 17-3-2021
:end:

|                |    | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 | PSO1 | PSO2 | PSO3 |
|                |    |  K3 |  K4 |  K5 |  K5 |  K6 |   - |   - |   - |   - |    - |    - |    - |   K5 |   K3 |   K6 |
| CO1            | K2 |   2 |   3 |   2 |   3 |   3 |   0 |   2 |   1 |   0 |    3 |    0 |    2 |    3 |    2 |    1 |
| CO2            | K3 |   2 |   3 |   2 |   3 |   3 |   0 |   2 |   1 |   0 |    3 |    0 |    2 |    3 |    2 |    1 |
| CO3            | K3 |   2 |   3 |   2 |   3 |   3 |   0 |   2 |   1 |   0 |    3 |    0 |    2 |    3 |    2 |    1 |
| CO4            | K2 |   2 |   3 |   3 |   3 |   3 |   0 |   2 |   1 |   0 |    3 |    0 |    2 |    3 |    1 |    1 |
| CO5            | K3 |   2 |   3 |   3 |   3 |   3 |   0 |   2 |   1 |   0 |    3 |    0 |    2 |    3 |    1 |    1 |
| Score          |    |  13 |  10 |   8 |   0 |   5 |   5 |   0 |   5 |   0 |    0 |    0 |    0 |    8 |   13 |    5 |
| Course Mapping |    |   3 |   2 |   2 |   0 |   1 |   1 |   0 |   1 |   0 |    0 |    0 |    0 |    2 |    3 |    1 |

#+begin_comment
 
#+end_comment

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- Explain the key aspects of traditional configuration management
- Demonstrate the microservices application  
- Deploy the microservice in a container 
- Explore Docker container networking services
- Modify the configuration techniques using kubernetes and Docker swarm 

{{{unit}}}
|UNIT I | TRADITIONAL | 9 |
Configuration management process : monitoring and control -- auditing -- testing -- incident and defect management -- problem management -- change management -- automation and tools -- lifecycle controls -- culture and organisation; Service asset and configuration management visions and strategies; Populating a CMDB  Process design : -- populate your CMDB; Case study monolithic application : Build the application -- Deploy the application.

#+begin_comment
...Included from Text book (1), chapter 6,8,10  
...Included from Text book (2) chapter 11
#+end_comment

{{{unit}}}
|UNIT II | MICROSERVICES | 9 |
An Introduction to Microservices:What Are Microservices? ; Switching to Microservices:Cost Components; Interprocess Communication:Putting It All Together; Case Study: Migration to Microservices -- Planning for Migration -- Planning for Migration -- Applying Microservices Criteria -- Converting to Microservices -- Application Build and Deployment.

#+begin_comment
...Included from Text Book 2, chapter 1,2,3,12

#+end_comment
 

{{{unit}}}
|UNIT III | CONTAINERS | 9 |
Docker Containers:Virtual Machines -- Containers -- Docker Architecture and Components -- The Power of Docker: A Simple Example;
Docker Interface:Key Docker Commands -- Dockerfile -- Docker Compose; Case Study: Containerizing a
Helpdesk Application : Containerizing Microservices -- Deploying the Catalog Microservice.

#+begin_comment
...Included from Text Book 2, chapter 5.7.13
#+end_comment
 

{{{unit}}}
|UNIT IV | NETWORKING AND DISCOVERY | 9 |

Docker Networking: Bridge Mode Networking -- Host Mode Networking -- Container Mode Networking -- No Networking -- Wrapping It Up; Service Discovery ;  Service Registry.

#+begin_comment
...Included from Text Book 3, chapter   2, 4
...Included from Text Book 2, chapter  9  
#+end_comment

{{{unit}}}
|UNIT V | ORCHESTRATION  | 9 |
Container Orchestration : Kubernetes -- Kubectl -- Master Node -- Worker Nodes -- Kubernetes Cluster;  Docker Swarm : Nodes -- Services -- Task -- Example: Swarm Cluster.

#+begin_comment
...Included from Text Book 2, chapter 9 
#+end_comment

** COURSE OUTCOMES
Upon completion of the course, the student should be able to:
- Summarize the traditional configuration principles both thoery and practically (K3)
- Develop a microservice (K3)
- Build a container and deploy a  microservice (K3)
- Learn the networking concepts in container (K2)
- Recognize the configutation features using Kubernetes and Docker swarm (K3).
      
** TEXT BOOKS
1. Shirley Lacy and David Norfolk, ``CONFIGURATION MANAGEMENT, Expert guidance for IT service managers and practitioners``, Revised edition,  BCS Learning and Development Ltd,   UK, 2014.
2. Parminder Singh Kocher Boston, Microservices and Containers, Addison-Wesley, 2018.
3. Michael Hausenblas, Docker Networking and Service Discovery, O'Reilly Publication, 2016.
** REFERENCES
1.  Thomas Uphill, Mastering Puppet, Second Edition,PACKT Publishing, 2016
2.  Scott Coulton, Puppet for Containerization,PACKT Publishing, 2016 
3.  Cesar de la Torre, Bill Wagner, Mike Rouses, .NET Microservices: Architecture for Containerized .NET Applications, Microsoft Corporation, V5.) Edition, 2020. 

