* <<<PE206>>> CYBER FORENSICS
:properties:
:author: Dr. A. Chamundeswari and Dr. S. Saraswathi
:date:  04-03-2021 09-03-2021 10-03-2021
:end:

#+startup: showall
** CO PO MAPPING :noexport:
#+NAME: co-po-mapping
|                |    | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 | PSO1 | PSO2 | PSO3 |
|                |    |  K3 |  K4 |  K5 |  K5 |  K6 |   - |   - |   - |   - |    - |    - |    - |   K5 |   K3 |   K6 |
| CO1            | K2 |   2 |   3 |   2 |   3 |   3 |   0 |   2 |   1 |   0 |    3 |    0 |    2 |    3 |    2 |    1 |
| CO2            | K3 |   2 |   3 |   2 |   3 |   3 |   0 |   2 |   1 |   0 |    3 |    0 |    2 |    3 |    2 |    1 |
| CO3            | K3 |   2 |   3 |   2 |   3 |   3 |   0 |   2 |   1 |   0 |    3 |    0 |    2 |    3 |    2 |    1 |
| CO4            | K2 |   2 |   3 |   3 |   3 |   3 |   0 |   2 |   1 |   0 |    3 |    0 |    2 |    3 |    1 |    1 |
| CO5            | K3 |   2 |   3 |   3 |   3 |   3 |   0 |   2 |   1 |   0 |    3 |    0 |    2 |    3 |    1 |    1 |
| Score          |    |  13 |  10 |   8 |   0 |   5 |   5 |   0 |   5 |   0 |    0 |    0 |    0 |    8 |   13 |    5 |
| Course Mapping |    |   3 |   2 |   2 |   0 |   1 |   1 |   0 |   1 |   0 |    0 |    0 |    0 |    2 |    3 |    1 |


{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

#+begin_comment
** REVISION 2018                                                   :noexport:
1. Almost the same as AU
2. The changes are listed below.
   - Unit-1: AU-Unit I included.
   - Unit-2: AU-Unit I topics included
     AU-Unit I data acquisition topics is elaborated
   - Unit-3: AU-Unit II topics included
     AU-Unit III topics included
   - Unit-4: AU-Unit III topics included
   - Unit-5: New tools topics included
     Ehtical hacking given in AU-Unit IV in SNU syllabus and V is not included in SNU.
3. Not Applicable
4. Five Course outcomes specified and aligned with units
5. Not Applicable
6. Did not include Kali Linux or Metasploit tools, as they are
   penetration testing tools to detect the vulnerabilities.
#+end_comment
#+begin_comment


** REVISION 2021                                                 
1. Almost the same as AU regulation 2017
#+end_comment

** COURSE OBJECTIVES
- To learn computer forensics and understand incident response
- To know the methods to collect and store digital evidence
- To understand the approaches to analyse and validate data
-  

{{{unit}}} 
| UNIT I | 	FUNDAMENTALS | 9 |
Understanding Incident Response : The incident response process -- The incident response charter --The incident response plan --
 The incident response playbook -- Testing the incident response framework ; Managing Cyber Incidents:  Investigating incidents  -- 
Incorporating containment strategies -- Getting back to normal – eradication and recovery; Fundamentals of Digital Forensics -- 
Legal aspects --  Digital forensics fundamentals  -- The digital forensics process -- Digital forensic lab;
 

#+begin_comment
...Text Book 1 : Chapter 1,2,3 
#+end_comment

{{{unit}}}

|UNIT II | EVIDENCE ACQUISITION   | 9 |
 Collecting Network Evidence  : An overview of network evidence  --  Firewalls and proxy logs --NetFlow -- Packet captures -- Wireshark -- Evidence collection;  Acquiring Host-Based Evidence Preparation :  Order of volatility  -- Evidence acquisition --  Acquiring volatile memory ;  Forensic Imaging : Understanding forensic imaging  -- Imaging tools -- Preparing a stage drive -- Using write blockers -- Imaging techniques


#+begin_comment
...Text Book 1 : Chapter 4,5,6
#+end_comment   
{{{unit}}}

|UNIT III | ANALYZING EVIDENCE | 9 |
Analyzing Network Evidence :  Network evidence overview -- Analyzing firewall and proxy logs ;  Analyzing System Memory : Memory analysis overview -- 
Memory analysis methodology ; Analyzing System Storage : Forensic platforms -- Autopsy -- MFT analysis -- Registry analysis; Analyzing Log Files : 
Understanding Windows logs ; Writing the Incident Report : Documentation overview;
 
#+begin_comment
 ...Text Book 1 : Chapter 7,8,9,10, 11
#+end_comment

{{{unit}}}
|UNIT IV |   | 9 |
Malware Analysis for Incident Response : Malware classifications -- Malware analysis overview -- Analyzing malware -- Dynamic analysis -- Leveraging Threat Intelligence -- Understanding threat intelligence -- Threat intelligence methodology -- Threat intelligence sources -- Threat intelligence platforms 
Using threat intelligence ;   
  
#+begin_comment
  ...Text Book 1 : Chapter 12, 13
#+end_comment
 
{{{unit}}}
|UNIT V | MALWARE AND THREAT INTELLIGENCE  | 9 |
 Introduction to Mobile Forensics : Why do we need mobile forensics? -- Mobile forensics -- The mobile phone evidence extraction process -- 
Practical mobile forensic approaches ;  Parsing Third-Party Application Files : Third-party application overview --
Encoding versus encryption -- Application data storage -- Forensic methods used to extract third-party application data ;
 
#+begin_comment
 ...Text Book 2 : Chapter 1, 13 
#+end_comment


\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Understand the basics of computer forensics 
- Infer different computer forensic tools to collect data
- Explain the tools used to Analyze and validate forensics data 
- Explian Ethical Hacking
- Explian Ethical Hacking in web

** TEXT BOOKS 
1. Gerard Johansen, Digital Forensics and Incident
Response, Second Edition, Packt Publishing, 2020. 
2. Rohit Tamma, Oleg Skulkin,  Heather Mahalik , Satish Bommisetty, Practical Mobile Forensics,  Third Edition,  Packt Publishing, 2018.

** REFERENCES 
1. Nelson, Phillips, Enfinger, Steuart, ``Computer Forensics and
   Investigations'', Cengage Learning, India Edition, 2008.
2. John R Vacca, ``Computer Forensics'', Cengage Learning, 2005.
3. Marjie T Britz, ``Computer Forensics and Cyber Crime: An
   Introduction'', 3rd Edition, Prentice Hall, 2013.
4. Marcella Jr, Albert, and Doug Menendez, ``Cyber Forensics: a Field
   Manual for Collecting, Examining, and Preserving Evidence of
   Computer Crimes'', Auerbach Publications, 2007.

   
