* <<<PE603>>> OBJECT ORIENTED ANALYSIS AND DESIGN
:properties:
:author: Dr. K. Valli Devi and Dr. S. Manisha
:date: 23.3.2021
:end:

#+begin_comment
1. Six Course outcomes specified and aligned with units
2. No change from R-2018

#+end_comment

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** Course Objectives
1. To understand and differentiate Unified Process from other approaches 
2. To understand object-oriented software design using UML's static diagrams
3. To understand software modeling using the UML's dynamic diagrams
4. To learn improving software design with design patterns
5. To learn testing the software with its requirements specification.

{{{unit}}}
|UNIT I | DEVELOPMENT PROCESS & USE-CASE DIAGRAM (STATIC)  | 9 |
Introduction to OOAD with OO Basics -- Unified process -- UML diagrams
-- Use case -- Case study -- The Next Gen POS system, Inception -- Use
case modelling -- Relating use cases -- Include, extend and
generalization -- When to use use-cases.

{{{unit}}}
|UNIT II | UNIFIED PROCESS & CLASS DIAGRAM (STATIC)		| 9 |
Class diagram -- Elaboration -- Domain model -- Finding conceptual
classes and description classes -- Associations -- Attributes --
Domain model refinement -- Finding conceptual class hierarchies --
Aggregation and composition -- Relationship between sequence diagrams
and use cases -- When to use class diagrams.

{{{unit}}}
|UNIT III | DYNAMIC & IMPLEMENTATION DIAGRAMS  | 9 |
Dynamic Diagrams: UML interaction diagrams -- System sequence diagram
-- Collaboration diagram -- When to use communication diagrams --
State machine diagram and modelling -- When to use state diagrams --
Activity diagram -- When to use activity diagrams.

Implementation Diagrams: UML package diagram -- When to use package
diagrams -- Component and deployment diagrams -- When to use component
and deployment diagrams.

{{{unit}}}
|UNIT IV | DESIGN PATTERNS | 9 |
Designing objects with responsibilities -- Creator -- Information
expert -- Low coupling -- High cohesion -- Controller design patterns
-- Creational -- Factory method -- Structural -- Bridge -- Adapter --
Behavioural -- Strategy -- Observer -- Applying GoF design patterns --
Mapping design to code.

{{{unit}}}
| UNIT V | TEST DRIVEN DEVELOPMENT AND REFACTORING | 9 |
Object oriented methodologies -- Software quality assurance -- Impact
of object orientation on testing -- Develop test cases and test plans.


\hfill *Total Periods: 45*

** COURSE OUTCOMES
Upon completion of this course, the students should be able to:
- Summarize software design with UML diagrams (K2)
- Inspect and implement projects using OO concepts (K4)
- Identify and map basic software requirements in UML mapping (K3)
- Analyze UML based software design into pattern based design using design patterns (K4)
- Test for any object-oriented software against its requirements (K4).
- Solve real world problems in teams by choosing suitable problem statement, design diagrams and apply suitable design patterns in software design with a clear documentation  of the UML diagrams and approach. (K3)

** TEXT BOOKS
1. Larman, Craig, ``Applying UML and Patterns'', Pearson Education
   Asia, 2008.
2. Ali Bahrami, ``Object Oriented Systems Development'', McGraw Hill
   International Edition, 1999.

** REFERENCES
1. Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides, ``Design
   patterns: Elements of Reusable Object Oriented Software'', Addison
   Wesley, 1995.
2. Martin Fowler, ``UML Distilled: A Brief Guide to the Standard
   Object Modeling Language'', 3rd edition, Addison Wesley, 2003.
3. Booch, G, Jacobson I, Rumbaugh J, ``The Unified Modeling Language
   User Guide'', Addison Wesley, 2008.
4. Roger S Pressman, ``Software Engineering -- A Practitioner's
   Approach'', 7th  edition, 2010.
5. Aditya P Mathur, ``Foundations of Software Testing -- Fundamental
   Algorithms and Techniques'', Dorling Kindersley (India) Pvt. Ltd.,
   Pearson Education, 2008.
   
   {{{CO-PO-PSO Matrix}}}
|    | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 | PSO1 | PSO2 | PSO3 |
| CO1 | 3 | 3 | 2 | 0 | 1 | 0 | 2 | 0 | 0 | 0 | 2 | 1 | 3 | 3 | 1 |
| CO2 | 3 | 3 | 2 | 2 | 2 | 0 | 2 | 0 | 0 | 0 | 2 | 1 | 3 | 3 | 2 |
| CO3 | 3 | 3 | 2 | 0 | 2 | 1 | 2 | 0 | 0 | 1 | 3 | 1 | 3 | 3 | 2 |
| CO4 | 3 | 3 | 3 | 0 | 1 | 0 | 2 | 0 | 0 | 0 | 2 | 1 | 3 | 3 | 1 |
| CO5 | 3 | 3 | 2 | 2 | 2 | 1 | 2 | 1 | 1 | 1 | 3 | 1 | 3 | 3 | 2 |
| CO6 | 3 | 3 | 2 | 0 | 2 | 0 | 2 | 3 | 3 | 3 | 2 | 1 | 3 | 3 | 2 |
