* <<<PE301>>> BAYESIAN DATA ANALYSIS
:properties:
:author: Dr. R.S.Milton and Ms. S. Angel Deborah
:date: 18-03-2021
:end:


#+startup: showall
** CO PO MAPPING :noexport:
#+NAME: co-po-mapping
|                |    | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 | PSO1 | PSO2 | PSO3 |
|                |    |  K3 |  K4 |  K5 |  K5 |  K6 |   - |   - |   - |   - |    - |    - |    - |   K5 |   K3 |   K6 |
| CO1            | K2 |   3 |   3 |   1 |   1 |   1 |   0 |   0 |   0 |   1 |    0 |    0 |    1 |    1 |    1 |    1 |
| CO2            | K3 |   3 |   3 |   3 |   3 |   1 |   0 |   0 |   0 |   1 |    0 |    0 |    1 |    3 |    2 |    3 |
| CO3            | K4 |   3 |   3 |   3 |   3 |   1 |   0 |   0 |   0 |   1 |    0 |    0 |    1 |    3 |    2 |    3 |
| CO4            | K4 |   3 |   3 |   3 |   3 |   1 |   0 |   0 |   0 |   1 |    0 |    0 |    1 |    3 |    2 |    3 |
| CO5            | K3 |   3 |   3 |   3 |   3 |   1 |   0 |   0 |   0 |   1 |    0 |    0 |    1 |    3 |    2 |    3 |
| CO6            | K3 |   3 |   3 |   3 |   3 |   3 |   0 |   0 |   1 |   3 |    3 |    0 |    1 |    3 |    3 |    3 |
| Score          |    |  18 |  18 |  16 |  16 |   8 |   0 |   0 |   1 |   8 |    3 |    0 |    5 |   16 |   12 |   16 |
| Course Mapping |    |   3 |   3 |   3 |   3 |   2 |   0 |   0 |   1 |   2 |    1 |    0 |    1 |    3 |    3 |    3 |


{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To know the fundamental concepts of probability theory, machine learning and statistics
- To explore One-parameter model, normal model and multivariate model
- To learn hierarchial modeling and non parametric models
- To know about the various bayesian computation.


{{{unit}}}
| UNIT I | BASICS OF PROBABILITY THEORY, MACHINE LEARNING AND STATISTICS | 9 |
Introduction:Bayes -- Estimating Probability of a Rare Event -- Building a Predictive Model; Probability:Events -- Partitions -- Bayes Rule -- Independene -- Random Variable -- Joint Distribution; Bayesian Inference in Applied Statistics.


{{{unit}}}
| UNIT II | ONE-PARAMETER MODELS, THE NORMAL MODEL  9 |
The Binomial Model: Inference -- Confidence Region; The Poisson model -- Posterior Inference; Exponential Families and Conjugate Priors; The Normal Model: Inference for the Mean, Conditional on the Variance -- Joint Inference for the Mean and Variance -- Prior Specification Based on Expectations -- The Normal Model for Non-Normal Data; The Multivariate Normal Model.

{{{unit}}}
|UNIT III | GROUP COMPARISONS AND HIERARCHICAL MODELING| 9 |
Group Comparisons: Comparing Two Groups -- Comparing Multiple Groups -- Exchangeability and Hierarchical Models; The Hierarchical Normal Model: Posterior Inference -- Hierarchical Modeling of Means and Variances -- Analysis of Math Score Data.

{{{unit}}}
|UNIT IV |  LINEAR REGRESSION AND NON PARAMETRIC MODEL | 9 |
The Linear Regression Model: Least Squares Estimation for the Oxygen Uptake Data; Bayesian Estimation for a Regression Model:  A Semiconjugate Prior Distribution -- Default and Weakly Informative Prior Distributions; Model Selection: Bayesian Model Comparison -- Gibbs Sampling and Model Averaging; Non-Parametric Model: Gaussian Process Models -- Finite Mixture Models.
{{{unit}}}
| UNIT V | BAYESIAN COMPUTATION | 9 |
Monte Carlo approximation: The Monte Carlo Method -- Posterior Inference for Arbitrary Functions -- Sampling from Predictive Distributions -- Posterior Predictive Model Checking; Posterior Approximation with the Gibbs Sampler: A Semiconjugate Prior Distribution -- Discrete Approximations -- Gibbs Sampling -- Metropolis-Hastings Algorithm and Gibbs Sampler.

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Summarize the basics of theory, machine learning and statistics(K2)
- Apply One-parameter model to develop a system (K3)
- Analysing data using hierarchical model (K4)
- Compare non-bayesian model with bayesian model (K4)
- Apply various Bayesion computation techiniques to solve a problem (K3)
- Solve a real time problem using any bayesian approach with clear documentation (K3)


      
** TEXT BOOKS

1. Peter D.Hoff, ``A  first course in Bayesian Statistical Methods'', Springer, 2009.


** REFERENCES
1. Andrew Gelman, John B.Carlin, Hal S. Stern HS, David B Dunson, Aki Vehtari, Dolland B.Rubin, ``Bayesian data analysis'', third edition, CRC press, 2013.
2. Richard McElreath, ``Statistical Rethinking'', second edition, CRC press, 2020.
3. John Kruschke, ``Doing Bayesian Data Analysis: A Tutorial with R, JAGS, and Stan'', second edition, Academic Press,2014
