* <<<PE402>>> USER EXPERIENCE DESIGN
:properties:
:author: Dr. S. Manisha and Dr. Y.V. Lokeswari
:date: 25.3.2021
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** CO-PO-PSO MATRIX :noexport:
|     | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 | PSO1 | PSO2 | PSO3 |
| CO1 |   3 |   3 |   2 |   0 |   1 |   0 |   0 |   0 |   0 |    0 |    0 |    0 |    3 |    3 |    1 |
| CO2 |   3 |   3 |   2 |   0 |   2 |   0 |   0 |   0 |   0 |    0 |    0 |    0 |    3 |    3 |    2 |
| CO3 |   3 |   3 |   2 |   0 |   2 |   0 |   0 |   0 |   0 |    0 |    0 |    0 |    3 |    3 |    2 |
| CO4 |   3 |   3 |   3 |   0 |   1 |   0 |   0 |   0 |   0 |    0 |    0 |    0 |    3 |    3 |    1 |
| CO5 |   3 |   3 |   2 |   0 |   2 |   0 |   0 |   0 |   0 |    0 |    0 |    0 |    3 |    3 |    2 |
| CO6 |   3 |   3 |   2 |   0 |   2 |   1 |   0 |   3 |   3 |    3 |    3 |    1 |    3 |    3 |    2 |

** COURSE OBJECTIVES
- To understand the goals and principles of interface design
- To study life cycle models and identify the requirements for interface design
- To learn effective prototypes for construction of user interface design
- To know about user testing
- To use tools to develop UI design for mobile app.

{{{unit}}}
| UNIT I | FOUNDATIONS OF INTERACTION DESIGN | 9 |
Interaction design -- Good and poor design -- Goals of interaction
design -- Design and usability principles; Conceptual models --
Interface metaphors -- Interaction paradigms -- From conceptual models
to physical design.

{{{unit}}}
| UNIT II | PROCESS AND REQUIREMENTS | 9 |
Activities of interaction design -- Key characteristics of interaction
design process -- Lifecycle models; Establish requirements --
Different kinds of requirements -- Data gathering; Data interpretation
and analysis -- Task description -- Task analysis.

{{{unit}}}
| UNIT III | DESIGN AND CONSTRUCTION | 9 |
Prototyping and construction -- Low-fidelity prototyping --
High-fidelity prototyping -- Compromises in prototyping --
Construction: from design to implementation; Conceptual Design: Moving
from requirements to first design -- Perspectives for developing a
conceptual model -- Expanding the conceptual model -- Scenarios and
prototypes in conceptual design; User-centered approach -- Ethnography
in design.

{{{unit}}}
| UNIT IV | EVALUATION AND TESTING | 9 |
What, why, and when to evaluate -- Hutchworld case study; Evaluation
paradigms and techniques; User testing -- Experiments -- Predictive
models.

{{{unit}}}
| UNIT V | MOBILE HCI | 9 |
Mobile Ecosystem: Platforms -- Application frameworks; Types of Mobile
Applications: Widgets -- Applications -- Games; Mobile Information
Architecture -- Mobile 2.0 -- Mobile Design: Elements of Mobile
Design-- Tools.

\hfill *Total Periods: 45*

** COURSE OUTCOMES
Upon the completion of the course the students should be able to: 
- Summarize the goals and principles of interface design (K2)
- Apply life cycle models and identify the requirements for interface
  design (K3)
- Construct user interface design using prototypes (K3)
- Develop user testing on user interface design (K3)
- Apply tools to develop UI design for mobile app (K3).
- Solve real world problems in teams by choosing suitable software problem and  applying best practices in programming  with a clear documentation  of problem statement and design interfaces. (K3)

** TEXT BOOKS
1. Preece J, Rogers Y, Sharp H, ``Interaction design: Beyond
   Human-Computer Interaction'', 4th edition John Wiley & Sons Ltd, 2015. (Unit 1 to 4)
2. Brian Fling, ``Mobile Design and Development'', 1st Edition ,
   O'Reilly Media Inc, 2009. (Unit 5)

** REFERENCES
1. Preece J, Rogers Y, Sharp H, Baniyon D, Holland S and Carey T,
   ``Human Computer Interaction'', Addison-Wesley, 1994.
2. B. Shneiderman, ``Designing the User Interface'', Addison Wesley
   2000 (Indian Reprint).
3. Alan Dix, Janet Finlay, Gregory Abowd, Russell Beale, ``Human
   Computer Interaction'', 3rd Edition, Pearson Education, 2004.
4. Bill Scott and Theresa Neil, ``Designing Web Interfaces'', 1st
   Edition, O'Reilly, 2009.

# 3. Yvonne Rogers, Helen Sharp, Jenny Preece, ``Interaction Design:
#   Beyond Human Computer Interaction'', 3rd Edition, Wiley, 2011

