* <<<PE504>>> COMPUTER VISION
:properties:
:author: Ms. R. Priyadharsini and Ms. P. Mirunalini
:date:  18-03-2021
:end:
#+startup: showall

** CO PO MAPPING :noexport:
#+NAME: co-po-mapping
|                |    | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 | PSO1 | PSO2 | PSO3 |
| CO1            | K3 |   2 |   3 |   1 |   3 |   3 |   0 |   0 |   0 |   2 |    0 |    0 |    0 |    3 |    0 |    1 |
| CO2            | K3 |   2 |   3 |   1 |   3 |   3 |   0 |   0 |   0 |   2 |    0 |    0 |    0 |    3 |    0 |    1 |
| CO3            | K2 |   2 |   2 |   3 |   3 |   3 |   0 |   1 |   0 |   0 |    0 |    0 |    0 |    2 |    0 |    1 |
| CO4            | K4 |   2 |   2 |   3 |   3 |   3 |   1 |   1 |   0 |   2 |    0 |    0 |    0 |    3 |    0 |    2 |
| CO5            | K3 |   2 |   3 |   1 |   3 |   3 |   1 |   0 |   0 |   2 |    0 |    0 |    0 |    3 |    0 |    2 |
| Score          |    |  10 |  13 |   9 |  15 |  15 |   2 |   2 |   0 |   8 |    0 |    0 |    0 |   14 |     0|    7 |
| Course Mapping |    |   2 |   3 |   2 |   3 |   3 |   1 |   1 |   0 |   2 |    0 |    0 |    0 |    3 |    0 |    2 |

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To explore the Low level vision features
- To learn and detect the Intermediate level features
- To familiarize the 3D vision, Depth estimation and 3D reconstruction methods
- To develop applications for Object recognition 
- To implement computer vision applications using Deep learning techniques


{{{unit}}}
|UNIT I | Image based Feature Extraction | 9 |
Introduction to Computer Vision and the challenges; Image based feature extraction: Thresholding Techniques -- Region growing methods -- Thresholding -- Adaptive thresholding -- Approaches to threshold selection -- Global valley approach to thresholding; Edge detection: Differential Gradient operator -- Hysteresis thresholding -- Canny operator -- Laplacian operator -- Active contours -- Level set -- Graph cut approach; Corner and Interest point detection: Second order derivative schemes -- Harris Interest point operators -- Local invariant feature detectors and descriptors; Texture;

{{{unit}}}
|UNIT II | Shapes and Regions | 9 |
Binary shape analysis: Skeletons and thinning -- Other measures for shape recognition; Boundary Pattern analyis: Boundary tracking procedures -- Centroidal profiles; Line detection: Hough transform -- Foot of normal method; Circle and Ellipse detection: Hough based scheme -- Ellipse detection methods; Case study: Human Iris Location;

{{{unit}}}
|UNIT III | 3D vision - Depth Estimation AND 3D Reconstruction: | 9 |
Feature-based alignment: 2D and 3D feature-based alignment -- pose estimation -- Geometric intrinsic calibration; Structure from Motion: Triangulation -- Two-frame structure from Motion -- Factorization -- Bundle adjustment; 
Stereo Correspondance: Epipolar geometry -- Sparse and Dense correspondence -- Multiview stereo; 3D Reconstruction: Shape from X -- Active rangefinding -- Surface representations -- Point-based representations;

{{{unit}}}
|UNIT IV | Object Recognition | 9 |
Object detection: Face detection -- Pedestrian detection; Face recognition: Eigen faces -- Active apperance and 3D shape models; Instance recognition: Geometric alignment; Category recognition: Bag of words -- Part based models; Context and scene understanding: Learning and large image collection; Applications for object recognition;

{{{unit}}}
|UNIT V | Deep Learning Techniques for Computer Vision | 9 |
Introduction to CNNs; Visualization of Kernels; Backprop-to-image/Deconvolution Methods;
CNNs for Detection: Background of Object Detection -- R-CNN -- Fast R-CNN -- Faster R-CNN; CNNs for Segmentation: FCN -- SegNet -- U-Net -- Mask-RCNN; Recurrent Neural Networks (RNNs): CNN and RNN Models for Video Understanding: Spatio-temporal Models -- Action/Activity Recognition

#+begin_comment
Removed: Image compression
Added: Case Study for Image recognition
#+end_comment

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Apply various low level feature detection methods (K3)
- Choose various feature analysis methods and transforms for intermediate level vision (K3)
- Explain depth estimation and 3D reconstruction (K2)
- Analyse the object recognition methods (K4)
- Build Deep learning models for computer vision (K3)
   
** TEXT BOOKS
1. Davies, E. Roy. Computer and machine vision: theory, algorithms, practicalities. Academic Press, 2012.
2. Shanmugamani, Rajalingappaa. Deep Learning for Computer Vision: Expert techniques to train advanced neural networks using TensorFlow and Keras. Packt Publishing Ltd, 2018. 
   
** REFERENCES
1. Szeliski, Richard. Computer vision: algorithms and applications. Springer Science & Business Media, 2010. 
2. D. L. Baggio et al., Mastering OpenCV with Practical Computer Vision Projects, Packt Publishing, 2012.
3. Jan Erik Solem, Programming Computer Vision with Python: Tools and algorithms for analyzing images, O'Reilly Media, 2012.
4. Mark Nixon and Alberto S. Aquado, ―Feature Extraction & Image Processing for Computer Vision, Third Edition, Academic Press, 2012.
5. Simon J. D. Prince, Computer Vision: Models, Learning, and Inference, Cambridge University Press, 2012.
