* <<<PE501>>> BIOINFORMATICS
:properties:
:author: Ms. S.Kavitha and Ms. P.Mirunalini
:date:  
:end:
#+startup: showall

** CO PO MAPPING :noexport:
#+NAME: co-po-mapping
|                |    | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 | PSO1 | PSO2 | PSO3 |
|                |    |  K3 |  K4 |  K5 |  K5 |  K6 |   - |   - |   - |   - |    - |    - |    - |   K3 |   K3 |   K6 |
| CO1            | K2 |   2 |   2 |   1 |   1 |   1 |   0 |   0 |   0 |   1 |    1 |    0 |    1 |    2 |    2 |    1 |
| CO2            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   0 |   1 |    1 |    0 |    1 |    3 |    3 |    1 |
| CO3            | K2 |   2 |   2 |   1 |   1 |   1 |   0 |   0 |   0 |   1 |    1 |    0 |    1 |    2 |    2 |    1 |
| CO4            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   1 |   0 |   1 |    1 |    0 |    1 |    3 |    3 |    1 |
| CO5            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   1 |   0 |   1 |    1 |    0 |    1 |    3 |    3 |    1 |
| Score          |    |  13 |  10 |   8 |   8 |   5 |   0 |   2 |   0 |   5 |    5 |    0 |    5 |   13 |   13 |    5 |
| Course Mapping |    |   3 |   2 |   2 |   2 |   1 |   0 |   1 |   0 |   1 |    1 |    0 |    1 |    3 |    3 |    1 |

#+begin_comment
- 1. Almost the same as EC8093  DIGITAL IMAGE PROCESSING in AU 2017
- 2. Change in Unit V (see the comment below unit V)
- 3. Unit - II in PCP1279(M.E. CSE Image Processing and Analysis)is
     split into Unit- II and III
     Image segmentation and Feature analysis methods in Unit- III of PCP1279 are moved to Unit - IV and 
     Unit - V respectively.
     The topic object recognition is added in Unit - V
- 4. Five Course outcomes specified and aligned with units
- 5. Not Applicable.
#+end_comment

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- The student should be made to:
-> Exposed to the need for Bioinformatics technologies
-> Able to transform biological data into knowledge and perform sequence data analysis
-> Be familiar with the modeling techniques
-> Exposed to Pattern Matching and Visualization
-> Learn microarray analysis


{{{unit}}}
|UNIT I | INTRODUCTION| 9 |
Need for Bioinformatics technologies – Overview of Bioinformatics technologies- Structural bioinformatics – 
Data format and processing – Secondary resources and applications –
Role of Structural bioinformatics - Biological Data Integration System.

{{{unit}}}
|UNIT II | DATAWAREHOUSING AND DATAMINING IN BIOINFORMATICS | 9 |
Bioinformatics data – Data warehousing architecture – data quality 
– Biomedical data analysis – DNA data analysis – Protein data analysis-
Machine learning – Neural network architecture and applications in biinformatics.

{{{unit}}}
|UNIT III | MODELING FOR BIOINFORMATICS | 9 |
Hidden Markov modeling for biological data analysis – Sequence identification 
–Sequence classification – multiple alignment generation – Comparative modeling – 
Protein modeling – genomic modeling – Probabilistic modeling – Bayesian networks 
– Boolean networks - Molecular modeling – Computer programs for molecular modeling.
 
{{{unit}}}
|UNIT IV | PATTERN MATCHING AND VISUALIZATION | 9 |
Gene regulation – motif recognition – motif detection – strategies for motif detection
– Visualization – Fractal analysis – DNA walk models – one dimension 
– two dimension – higher dimension – Game representation of Biological sequences 
– DNA, Protein, Amino acid sequences.

{{{unit}}}
|UNIT V | MICROARRAY ANALYSIS | 9 |
Microarray technology for genome expression study – image analysis for data extraction 
– preprocessing – segmentation – gridding – spot extraction – normalization, filtering – cluster analysis
– gene network analysis – Compared Evaluation of Scientific Data Management Systems
– Cost Matrix – Evaluation model - Benchmark – Tradeoffs.
 

#+begin_comment

#+end_comment

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
-> understand the need for Bioinformatics technologies
-> Perform sequence data analysis
-> Develop models for biological data.
-> Apply pattern matching techniques to bioinformatics data – protein data genomic data.
-> Apply micro array technology for genomic expression study.
   
** TEXT BOOKS
1. Yi-Ping Phoebe Chen (Ed), “BioInformatics Technologies”, First Indian Reprint, Springer Verlag, 2007.
2. Rui Jiang • Xuegong Zhang • Michael Q. Zhang, "Basics of Bioinformatics", Tsinghua University Press, Springer, 2013
2. JIN XIONG, "Essential Bioinformatics", Cambridge Unversity Press, 2006
   
** REFERENCES
1. Bryan Bergeron, “Bio Informatics Computing”, Second Edition, Pearson Education, 2003.
2. Arthur M Lesk, “Introduction to Bioinformatics”, Second Edition, Oxford University Press, 2005
