* <<<PE607>>> PARALLEL ALGORITHMS
:properties:
:author: Dr. Venkata Vara Prasad and Mr. V. Balasubramanian 
:date: 
:end:

#+startup: showall

#+begin_comment
- 1. Almost the same as AU 
- 2. Not Applicable
- 3. Five Course outcomes specified and aligned with units
- 4. Not Applicable
#+end_comment


{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To understand the design of parallel algorithms
- To select suitable procedures for parallel algorithms
- To understand different parallel architectures and models of computation
- To introduce the various classes of parallel algorithms
- To study parallel algorithms for basic problems. 

{{{unit}}}
| UNIT I | INTRODUCTION | 9 |
Theoretical models of parallel computation: variants of the PRAM
model, interconnection networks, synchronous and asynchronous models -
Computational Models- Intearcting Variables - Performance of parallel
algorithms.

{{{unit}}}
| UNIT II | TECHNIQUES | 9 |
Basic techniques: balanced trees - recursive doubling - divide and
conquer - partitioning - pipelining - accelerated cascading - symmetry
Breaking

{{{unit}}}
| UNIT III | LIST TECHNIQUES | 9 |
List ranking - the Euler tour technique - tree contraction - Lowest
Common Ancestors - Searching - Merging - sorting

{{{unit}}}
| UNIT IV | GRAPH ALGORITHMS | 9 |
Connected Components - Colouring - Minimal spanning tree - Shortest
path algorithm - Parallel algorithms on interconnection networks and
other architectures

{{{unit}}}
| UNIT V | LIMITS TO PARALLELIZABILITY | 9 |
String Matching - Text analysis - Pattern Matching - Limits to
parallelizability - NC-reductions - P-completeness

** TEXT BOOKS
1. J. Jaja, An Introduction to Parallel Algorithms, Addison Wesley, 1992.
2. F. T. Leighton, Introduction to Parallel Algorithms and Architectures: Arrays,Trees,Hypercubes,Morgan Kaufmann Publishers,San Mateo,California,1992.

** REFERENCES
1. J. H. Reif, Synthesis of Parallel Algorithms, Morgan Kaufmann Publishers, San Mateo, California.
2. S. G. Akl, Parallel Computation: Models and Methods, Prentice Hall, 1996.
