* <<<PE601>>> BIOINFORMATICS
:properties:
:author: Dr.S.Kavitha and Dr.P.Mirunalini
:date: 17-03-2021  
:end:
#+startup: showall

** CO PO MAPPING :noexport:
#+NAME: co-po-mapping
|                |    | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 | PSO1 | PSO2 | PSO3 |
|                |    |  K3 |  K4 |  K5 |  K5 |  K6 |   - |   - |   - |   - |    - |    - |    - |   K3 |   K3 |   K6 |
| CO1            | K2 |   2 |   2 |   1 |   1 |   1 |   0 |   0 |   0 |   1 |    1 |    0 |    1 |    2 |    2 |    1 |
| CO2            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   0 |   1 |    1 |    0 |    1 |    3 |    3 |    1 |
| CO3            | K2 |   2 |   2 |   1 |   1 |   1 |   0 |   0 |   0 |   1 |    1 |    0 |    1 |    2 |    2 |    1 |
| CO4            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   1 |   0 |   1 |    1 |    0 |    1 |    3 |    3 |    1 |
| CO5            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   1 |   0 |   1 |    1 |    0 |    1 |    3 |    3 |    1 |
| Score          |    |  13 |  10 |   8 |   8 |   5 |   0 |   2 |   0 |   5 |    5 |    0 |    5 |   13 |   13 |    5 |
| Course Mapping |    |   3 |   2 |   2 |   2 |   1 |   0 |   1 |   0 |   1 |    1 |    0 |    1 |    3 |    3 |    1 |

#+begin_comment
- Few changes are done from AU 2013, 7th semester Elective course on Bioinformatics
- Yet to do mapping
#+end_comment

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
The student should be made to:
- Understand the concept and need of Bioinformatics 
- Transform biological data into knowledge and perform data analysis
- Learn the machine learning algorithms for bioinformatics
- Leran hidden morkov modeling and probabilistic modeling 
- Know the importance of microarray data analysis


{{{unit}}}
|UNIT I | INTRODUCTION | 9 |
Introduction to Bioinformatics: Need for Bioinformatics technologies -- Overview of Bioinformatics technologies; Overview of structural bioinformatics: Organization of Structural bioinformatics -– Primary resource: protein data bank -- Secondary resources and applications.

{{{unit}}}
|UNIT II | DATAWAREHOUSING AND DATAMINING IN BIOINFORMATICS | 9 |
Data warehousing in Bioinformatics: Bioinformatics data -- Transforming data to knowledge -- Data warehousing architecture -- Data quality; Data mining for Bioinformatics: Biomedical data analysis -- DNA data analysis -- Protein data analysis.

{{{unit}}}
|UNIT III | MACHINE LEARNING IN BIOINFORMATICS | 9 |
Machine learning in Bioinformatics: Artificia Neural network -- Neural network architecture and applications -- Genetic algorithm -- Fuzzy system.
 
{{{unit}}}
|UNIT IV | MODELING FOR BIOINFORMATICS | 9 |
Modeling for Bioinformatics: Hidden Markov modeling for biological data analysis --  Comparative modeling -- Probabilistic modeling -- Molecular modeling. 

{{{unit}}}
|UNIT V | MICROARRAY DATA ANALYSIS | 9 |
Microarray Data Analysis: Microarray technology for genome expression study -- Image analysis for data extraction -- Data Analysis for Pattern Discovery.

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Explain the concept and need of Bioinformatics (K2)
- Identify the genome and protein data and its equivalent storage and mining process (K3)
- Apply machine learning algorithms for bioinformatics dataset (K3)
- Make use of hidden morkov modeling and probabilistic modeling for bioinformatics dataset (K3)
- Infer the importance of microarray data analysis (K2)
   
** TEXT BOOKS
1. Yi-Ping Phoebe Chen (Ed), “BioInformatics Technologies”, First Indian Reprint, Springer Verlag, 2007.

** REFERENCES
1. Arthur M Lesk, “Introduction to Bioinformatics”, Fourth Edition, Oxford University Press, 2008
2. Rui Jiang • Xuegong Zhang • Michael Q. Zhang, "Basics of Bioinformatics", Tsinghua University Press, Springer, 2013   
