* <<<PE606>>> SOFTWARE DEFINED NETWORKS
:properties:
:author: HSH, NS
:date: 13-03-2021
:end:
#+startup: showall
{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To understand the need for SDN and it's data plane operations
- To understand the functions of control plane
- To comprehend the the migration of networking functions to SDN environment
- To explore various techniques of network function virtualization
- To comprehend the concepts of network virtualizaton

{{{unit}}}
| UNIT I |  SDN: BACKGROUND AND DATA PLANE| 9 |
Evolving Network Requirements -- The SDN Approach  -- SDN- and NFV-Related Standards
-- SDN Data Plane -- OpenFlow Logical Network Device  -- OpenFlow Protocol.


{{{unit}}}
| UNIT II | SDN CONTROL PLANE | 9 |
SDN Control Plane Architecture: Southbound Interface,  Northbound Interface -- Control Plane Functions --  ITU-T Model  -- OpenDaylight -- REST -- Cooperation and Coordination Among Controllers.


{{{unit}}}
| UNIT III | SDN Application Plane | 9 |
SDN Application Plane Architecture -- Network Services Abstraction Layer -- Traffic Engineering  -- Measurement and Monitoring --
Security -- Data Center Networking -- Mobility and Wireless -- Information-Centric Networking.

{{{unit}}}
| UNIT IV | NETWORK FUNCTION VIRTUALIZATION | 9 |
NFV Concepts -- Benefits and Requirements -- Reference Architecture -- NFV Infrastructure -- Virtualized Network Functions
-- NFV Management and Orchestration -- NFV Use Cases -- SDN and NFV.

{{{unit}}}
|UNIT V| NETWORK VIRTUALIZATION |9|
Virtual LANs  --  OpenFlow VLAN Support --  Virtual Private Networks --
Network Virtualization -- OpenDaylight’s Virtual Tenant Network.-- CoSoftware-Defined Infrastructure. 

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Describe the motivation for SDN and its data plane (K2)
- Illutrate the functions of control plane (K2)
- Apply SDN motivations to Networking applications (K3)
- Describe various operations of Network function virtualization (K2)
- Explain the concept of network virtualization (K2).

** TEXT BOOKS
1. William Stallings, ``Foundations of Modern Networking: SDN, NFV, QoE, IoT, and Cloud'', Pearson, 1st Edition, 2015.

** REFERENCES
1. Thomas D. Nadeau, Ken Gray,``SDN: Software Defined Networks'', O'Reilly Media, 2013.
2. Fei Hu , ``Network Innovation through OpenFlow and SDN: Principles and Design'', 1st Edition, CRC Press, 2014.
3. Paul Goransson Chuck Black Timothy Culver, ``Software Defined Networks: A Comprehensive Approach'', 2nd Edition, Morgan Kaufmann Press, 2016.
4. Oswald Coker, Siamak Azodolmolky,"Software-Defined Networking with OpenFlow", 2nd Edition, O'Reilly Media, 2017.

