* <<<PE605>>> REINFORCEMENT LEARNING
:properties:
:author: Ms. M. Saritha and Ms. S. Rajalakshmi
:date: 15-03-2021
:end:

#+begin_comment
- 1. 
#+end_comment

#+startup: showall

{{{credits}}}
|L|T|P|C|
|3|0|0|3|

** COURSE OBJECTIVES
- To understand the basics of reinforcement learning techniques
- To explore various methods used in reinforcement learning
- To apply reinforcement learning techniques for various case studies.

| UNIT I | INTRODUCTION | 9 |
Reinforcement Learning -- Examples -- Elements of Reinforcement Learning -- Limitations and Scope -- Tic-Tac-Toe; Multi-armed Bandits; Finite Markov Decision Processes.

| UNIT II | TABULAR SOLUTION METHODS | 11 |
Dynamic Programming; Monte Carlo Methods: Prediction -- Estimation of Action Values -- Control -- Control without Exploring Starts -- Off-policy Prediction via Importance Sampling -- Incremental Implementation -- Off-policy Monte Carlo Control; Temporal-Difference Learning.

| UNIT III |  INTEGRATION OF TABULAR METHODS | 9 |
n-step Bootstrapping: TD Prediction -- Sarsa -- Off-policy Learning; Planning and Learning with Tabular Methods.

| UNIT IV |  | APPROXIMATE SOLUTION METHODS | 10 |
On-policy Prediction with Approximation; On-policy Control with Approximation; Eligibility Traces: The \lambda-return -- TD(") -- n-step Truncated "-return Methods -- Online "-return Algorithm -- True Online TD("); Policy Gradient Methods. 

| UNIT V | APPLICATIONS AND CASE STUDIES | 6 |
TD-Gammon; Watson’s Daily-Double Wagering; Optimizing Memory Control; Human-level Video Game Play.

#+begin_comment
- 1. 
#+end_comment

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- To outline the elements of reinforcement learning (K2)
- To illustrate tabular solution methods for various problems (K2)
- To explain approximate solution methods for different problems (K2)
- Apply reinforcement learning techniques for various case studies (K3).

** TEXT BOOKS
1. Richard S. Sutton & Andrew G. Barto, ``Reinforcement Learning: An Introduction'', The MIT Press, 2nd Edition, 2018.
2. Marco Wiering & Martijn van Otterlo, ``Reinforcement Learning State-of-the-Art'', Springer, 2012.

** REFERENCES
1.  Boris Belousov, Hany Abdulsamad, Pascal Klink, Simone Parisi & Jan Peters, ``Reinforcement Learning Algorithms: Analysis and Applications'', Springer, 1st edition, 2021. 
2.  Micheal Lanham, ``Hands-On Reinforcement Learning for Games'', Packt Publishing Ltd., 2020.
3.  Taweh Beysolow II, ``Applied Reinforcement Learning with Python'', Apress, 2019.
4.  Dimitri Bertsekas, ``Reinforcement Learning and Optimal Control'', Athena Scientific, 2019. 
